import { TeacherSideBarData } from "@/resource/teachers/sidebarData";

import "@app/styles/globals.css";
import { ProfileData } from "@/resource/teachers/sidebarData";
import NewTeacherSidebar from "../../../components/common/SideBar/TeacherSidebar";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import HomeFooter from "@/components/common/Footer/HomeFooter";

export const metadata = {
  title: "OBAC-teacher.ac.th",
  description: "Generated by FavTeam",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="min-h-dvh flex flex-col">
        <ToastContainer
          position="bottom-right"
          hideProgressBar
          className="z-50"
        />

        <NewTeacherSidebar
          menuItems={TeacherSideBarData.menuItems}
          profileData={ProfileData}
        />

        <main className="flex-1 pt-16 lg:pl-16 flex">
          <div className="m-auto w-full">{children}</div>
        </main>

        <HomeFooter />
      </body>
    </html>
  );
}
