import { TeacherSideBarData } from "@/resource/teachers/sidebarData";

import "@app/styles/globals.css";
import { ProfileData } from "@/resource/teachers/sidebarData";
import NewTeacherSidebar from "../../../components/common/SideBar/TeacherSidebar";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import HomeFooter from "@/components/common/Footer/HomeFooter";

export const metadata = {
  title: "OBAC-teacher.ac.th",
  description: "Generated by FavTeam",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col  min-h-screen">
        <ToastContainer
          position="bottom-right"
          hideProgressBar
          className="z-50"
        />
        <NewTeacherSidebar
          menuItems={TeacherSideBarData.menuItems}
          profileData={ProfileData}
        />
        <div className="pt-20 lg:pl-[65px] flex-grow">{children}</div>
        <HomeFooter/>
      </body>
    </html>
  );
}
