// import {
//   filterProgramsParamsData,
//   GetAllStudent,
//   GetAllStudentTableDto,
//   GetStudentListByGroupIDDto,
// } from "@/dto/studentDto";
// import { StudentGroupScheduleStatus } from "@/dto/studentGroupItem";
// import { TeacherDetailAndScheduleResponse } from "@/dto/teacherDto";

// export const mockStudents: GetAllStudent[] = [
//   {
//     studentId: 1,
//     firstName: "Somchai",
//     lastName: "Suksan",
//     thaiName: "สมชาย",
//     thaiLastName: "สุขสันต์",
//     gender: "ชาย",
//     groupName: "วิศวกรรมศาสตร์ ปี 1",
//     studentGroupId: 101,
//     studentCode: "6501001",
//     thaiId: "1103700456721",
//     email: "somchai@example.com",
//     phoneNumber: "0812345678",
//     address: "123 ถ.สุขุมวิท กรุงเทพฯ",
//     nationality: "ไทย",
//     religion: "พุทธ",
//     role: "student",
//     userId: "u001",
//     isActive: true,
//     class: "ป.ตรี",
//     enrollYear: 2022,
//     currentYear: 1,
//     graduateYear: 2026,
//     currentRoom: "101",
//     programId: 1,
//     programName: "วิศวกรรมคอมพิวเตอร์",
//     facultyId: 10,
//     facultyName: "คณะวิศวกรรมศาสตร์",
//     birthDate: "2004-05-01",
//   },
//   {
//     studentId: 2,
//     firstName: "Suchada",
//     lastName: "Wongchai",
//     thaiName: "สุชาดา",
//     thaiLastName: "วงศ์ชัย",
//     gender: "หญิง",
//     groupName: "บริหารธุรกิจ ปี 2",
//     studentGroupId: 102,
//     studentCode: "6402002",
//     thaiId: "1103700456722",
//     email: "suchada@example.com",
//     phoneNumber: "0823456789",
//     address: "456 ถ.ราชดำริ กรุงเทพฯ",
//     nationality: "ไทย",
//     religion: "คริสต์",
//     role: "student",
//     userId: "u002",
//     isActive: true,
//     class: "ป.ตรี",
//     enrollYear: 2021,
//     currentYear: 2,
//     graduateYear: 2025,
//     currentRoom: "202",
//     programId: 2,
//     programName: "การตลาด",
//     facultyId: 20,
//     facultyName: "คณะบริหารธุรกิจ",
//     birthDate: "2003-08-12",
//   },
//   {
//     studentId: 3,
//     firstName: "Anan",
//     lastName: "Kaewdee",
//     thaiName: "อนันต์",
//     thaiLastName: "แก้วดี",
//     gender: "ชาย",
//     groupName: "วิทยาการคอมพิวเตอร์ ปี 3",
//     studentGroupId: 103,
//     studentCode: "6303003",
//     thaiId: "1103700456723",
//     email: "anan@example.com",
//     phoneNumber: "0834567890",
//     address: "789 ถ.เพชรเกษม กรุงเทพฯ",
//     nationality: "ไทย",
//     religion: "อิสลาม",
//     role: "student",
//     userId: "u003",
//     isActive: true,
//     class: "ป.ตรี",
//     enrollYear: 2020,
//     currentYear: 3,
//     graduateYear: 2024,
//     currentRoom: "303",
//     programId: 3,
//     programName: "วิทยาการคอมพิวเตอร์",
//     facultyId: 30,
//     facultyName: "คณะวิทยาศาสตร์",
//     birthDate: "2002-11-20",
//   },
//   {
//     studentId: 4,
//     firstName: "Napat",
//     lastName: "Siri",
//     thaiName: "นภัทร",
//     thaiLastName: "ศิริ",
//     gender: "ชาย",
//     groupName: "นิเทศศาสตร์ ปี 1",
//     studentGroupId: 104,
//     studentCode: "6504004",
//     thaiId: "1103700456724",
//     email: "napat@example.com",
//     phoneNumber: "0845678901",
//     address: "321 ถ.สีลม กรุงเทพฯ",
//     nationality: "ไทย",
//     religion: "พุทธ",
//     role: "student",
//     userId: "u004",
//     isActive: true,
//     class: "ป.ตรี",
//     enrollYear: 2022,
//     currentYear: 1,
//     graduateYear: 2026,
//     currentRoom: "104",
//     programId: 4,
//     programName: "สื่อสารมวลชน",
//     facultyId: 40,
//     facultyName: "คณะนิเทศศาสตร์",
//     birthDate: "2004-01-15",
//   },
//   {
//     studentId: 5,
//     firstName: "Pimchanok",
//     lastName: "Thepsiri",
//     thaiName: "พิมพ์ชนก",
//     thaiLastName: "เทพศิริ",
//     gender: "หญิง",
//     groupName: "ครุศาสตร์ ปี 4",
//     studentGroupId: 105,
//     studentCode: "6205005",
//     thaiId: "1103700456725",
//     email: "pimchanok@example.com",
//     phoneNumber: "0856789012",
//     address: "888 ถ.บางนา-ตราด สมุทรปราการ",
//     nationality: "ไทย",
//     religion: "พุทธ",
//     role: "student",
//     userId: "u005",
//     isActive: false,
//     class: "ป.ตรี",
//     enrollYear: 2019,
//     currentYear: 4,
//     graduateYear: 2023,
//     currentRoom: "404",
//     programId: 5,
//     programName: "การศึกษาปฐมวัย",
//     facultyId: 50,
//     facultyName: "คณะครุศาสตร์",
//     birthDate: "2001-07-22",
//   },
//   {
//     studentId: 6,
//     firstName: "Jirapat",
//     lastName: "Thongdee",
//     thaiName: "จิรภัทร",
//     thaiLastName: "ทองดี",
//     gender: "ชาย",
//     groupName: "ศิลปกรรม ปี 2",
//     studentGroupId: 106,
//     studentCode: "6406006",
//     thaiId: "1103700456726",
//     email: "jirapat@example.com",
//     phoneNumber: "0867890123",
//     address: "999 ถ.ประชาชื่น นนทบุรี",
//     nationality: "ไทย",
//     religion: "พุทธ",
//     role: "student",
//     userId: "u006",
//     isActive: true,
//     class: "ป.ตรี",
//     enrollYear: 2021,
//     currentYear: 2,
//     graduateYear: 2025,
//     currentRoom: "205",
//     programId: 6,
//     programName: "ศิลปะการแสดง",
//     facultyId: 60,
//     facultyName: "คณะศิลปกรรมศาสตร์",
//     birthDate: "2003-10-10",
//   },
//   {
//     studentId: 7,
//     firstName: "Warin",
//     lastName: "Chanthara",
//     thaiName: "วริน",
//     thaiLastName: "จันทรา",
//     gender: "หญิง",
//     groupName: "แพทยศาสตร์ ปี 1",
//     studentGroupId: 107,
//     studentCode: "6507007",
//     thaiId: "1103700456727",
//     email: "warin@example.com",
//     phoneNumber: "0878901234",
//     address: "101 ถ.งามวงศ์วาน กรุงเทพฯ",
//     nationality: "ไทย",
//     religion: "พุทธ",
//     role: "student",
//     userId: "u007",
//     isActive: true,
//     class: "ป.ตรี",
//     enrollYear: 2022,
//     currentYear: 1,
//     graduateYear: 2028,
//     currentRoom: "107",
//     programId: 7,
//     programName: "แพทยศาสตร์",
//     facultyId: 70,
//     facultyName: "คณะแพทยศาสตร์",
//     birthDate: "2004-09-03",
//   },
//   {
//     studentId: 8,
//     firstName: "Pongsak",
//     lastName: "Yamdee",
//     thaiName: "พงศ์ศักดิ์",
//     thaiLastName: "ยามดี",
//     gender: "ชาย",
//     groupName: "เกษตรศาสตร์ ปี 3",
//     studentGroupId: 108,
//     studentCode: "6308008",
//     thaiId: "1103700456728",
//     email: "pongsak@example.com",
//     phoneNumber: "0889012345",
//     address: "505 ถ.วิภาวดี กรุงเทพฯ",
//     nationality: "ไทย",
//     religion: "พุทธ",
//     role: "student",
//     userId: "u008",
//     isActive: true,
//     class: "ป.ตรี",
//     enrollYear: 2020,
//     currentYear: 3,
//     graduateYear: 2024,
//     currentRoom: "308",
//     programId: 8,
//     programName: "เทคโนโลยีการเกษตร",
//     facultyId: 80,
//     facultyName: "คณะเกษตรศาสตร์",
//     birthDate: "2002-06-30",
//   },
//   {
//     studentId: 9,
//     firstName: "Kanya",
//     lastName: "Srisuk",
//     thaiName: "กัญญา",
//     thaiLastName: "ศรีสุข",
//     gender: "หญิง",
//     groupName: "นิติศาสตร์ ปี 4",
//     studentGroupId: 109,
//     studentCode: "6209009",
//     thaiId: "1103700456729",
//     email: "kanya@example.com",
//     phoneNumber: "0890123456",
//     address: "202 ถ.แจ้งวัฒนะ กรุงเทพฯ",
//     nationality: "ไทย",
//     religion: "พุทธ",
//     role: "student",
//     userId: "u009",
//     isActive: false,
//     class: "ป.ตรี",
//     enrollYear: 2019,
//     currentYear: 4,
//     graduateYear: 2023,
//     currentRoom: "409",
//     programId: 9,
//     programName: "นิติศาสตร์",
//     facultyId: 90,
//     facultyName: "คณะนิติศาสตร์",
//     birthDate: "2001-03-17",
//   },
//   {
//     studentId: 10,
//     firstName: "Thanawat",
//     lastName: "Meechai",
//     thaiName: "ธนวัฒน์",
//     thaiLastName: "มีชัย",
//     gender: "ชาย",
//     groupName: "เศรษฐศาสตร์ ปี 2",
//     studentGroupId: 110,
//     studentCode: "6410010",
//     thaiId: "1103700456730",
//     email: "thanawat@example.com",
//     phoneNumber: "0801234567",
//     address: "303 ถ.ราชพฤกษ์ กรุงเทพฯ",
//     nationality: "ไทย",
//     religion: "พุทธ",
//     role: "student",
//     userId: "u010",
//     isActive: true,
//     class: "ป.ตรี",
//     enrollYear: 2021,
//     currentYear: 2,
//     graduateYear: 2025,
//     currentRoom: "210",
//     programId: 10,
//     programName: "เศรษฐศาสตร์",
//     facultyId: 100,
//     facultyName: "คณะเศรษฐศาสตร์",
//     birthDate: "2003-12-25",
//   },
// ];

// export const mockGroupdata: filterProgramsParamsData[] = [
//   {
//     facultyName: "คณะวิศวกรรมศาสตร์",
//     programName: "วิศวกรรมคอมพิวเตอร์",
//     class: "ปวช",
//     groupId: "g001",
//     groupName: "1/1",
//     groupCode: "ENG-CPE-1A",
//   },
//   {
//     facultyName: "คณะบริหารธุรกิจ",
//     programName: "การบัญชี",
//     class: "ปวช",
//     groupId: "g002",
//     groupName: "2/3",
//     groupCode: "BUS-ACC-2B",
//   },
//   {
//     facultyName: "คณะนิเทศศาสตร์",
//     programName: "การสื่อสารมวลชน",
//     class: "ปวช",
//     groupId: "g003",
//     groupName: "3/2",
//     groupCode: "COMM-MED-1A",
//   },
//   {
//     facultyName: "คณะครุศาสตร์",
//     programName: "การศึกษาปฐมวัย",
//     class: "ปวส",
//     groupId: "g004",
//     groupName: "1/2",
//     groupCode: "EDU-ECE-3C",
//   },
//   {
//     facultyName: "คณะศิลปกรรมศาสตร์",
//     programName: "ศิลปะการแสดง",
//     class: "ปวส",
//     groupId: "g005",
//     groupName: "2/1",
//     groupCode: "FA-PER-2B",
//   },
//   {
//     facultyName: "คณะวิทยาศาสตร์",
//     programName: "ชีววิทยา",
//     class: "ปวส",
//     groupId: "g006",
//     groupName: "2/3",
//     groupCode: "SCI-BIO-4D",
//   },
//   {
//     facultyName: "คณะนิติศาสตร์",
//     programName: "นิติศาสตร์",
//     class: "ปวช",
//     groupId: "g007",
//     groupName: "3/3",
//     groupCode: "LAW-LAW-3C",
//   },
//   {
//     facultyName: "คณะเศรษฐศาสตร์",
//     programName: "เศรษฐศาสตร์",
//     class: "ปวช",
//     groupId: "g008",
//     groupName: "1/2",
//     groupCode: "ECO-ECO-1A",
//   },
//   {
//     facultyName: "คณะเกษตรศาสตร์",
//     programName: "เกษตรทั่วไป",
//     class: "ปวส",
//     groupId: "g009",
//     groupName: "2/2",
//     groupCode: "AGR-GEN-2B",
//   },
//   {
//     facultyName: "คณะแพทยศาสตร์",
//     programName: "แพทยศาสตร์",
//     class: "ปวส",
//     groupId: "g010",
//     groupName: "1/3",
//     groupCode: "MED-MED-1A",
//   },
// ];

// export const mockStudentTableData: GetAllStudentTableDto[] = [
//   {
//     studentId: 1,
//     studentCode: "65010001",
//     thaiName: "สมชาย ใจดี",
//     class: "ปวช",
//     currentYear: 1,
//     facultyName: "คณะวิศวกรรมศาสตร์",
//     subProgramName: "ไฟฟ้ากำลัง",
//     programName: "วิศวกรรมไฟฟ้า",
//   },
//   {
//     studentId: 2,
//     studentCode: "65010002",
//     thaiName: "สุชาดา สุวรรณ",
//     class: "ปวช",
//     currentYear: 2,
//     facultyName: "คณะบริหารธุรกิจ",
//     subProgramName: "การบัญชีขั้นต้น",
//     programName: "การบัญชี",
//   },
//   {
//     studentId: 3,
//     studentCode: "64010003",
//     thaiName: "อนันต์ แก้วใส",
//     class: "ปวส",
//     currentYear: 1,
//     facultyName: "คณะวิทยาศาสตร์",
//     subProgramName: "เทคโนโลยีสารสนเทศ",
//     programName: "วิทยาการคอมพิวเตอร์",
//   },
//   {
//     studentId: 4,
//     studentCode: "64010004",
//     thaiName: "ณัฐวุฒิ อินทร์ดี",
//     class: "ปวส",
//     currentYear: 2,
//     facultyName: "คณะนิเทศศาสตร์",
//     subProgramName: "โฆษณาและประชาสัมพันธ์",
//     programName: "นิเทศศาสตร์",
//   },
//   {
//     studentId: 5,
//     studentCode: "63010005",
//     thaiName: "พิมพ์ชนก ใจงาม",
//     class: "ปวช",
//     currentYear: 3,
//     facultyName: "คณะศิลปกรรมศาสตร์",
//     subProgramName: "ดนตรีไทย",
//     programName: "ศิลปะการแสดง",
//   },
//   {
//     studentId: 6,
//     studentCode: "64020006",
//     thaiName: "จีระศักดิ์ เรืองโรจน์",
//     class: "ปวส",
//     currentYear: 1,
//     facultyName: "คณะครุศาสตร์",
//     subProgramName: "การสอนเด็กเล็ก",
//     programName: "การศึกษาปฐมวัย",
//   },
//   {
//     studentId: 7,
//     studentCode: "63020007",
//     thaiName: "วรินทร์ ภูธร",
//     class: "ปวช",
//     currentYear: 2,
//     facultyName: "คณะเกษตรศาสตร์",
//     subProgramName: "พืชศาสตร์",
//     programName: "เทคโนโลยีการเกษตร",
//   },
//   {
//     studentId: 8,
//     studentCode: "63030008",
//     thaiName: "จิตรา ศรีประเสริฐ",
//     class: "ปวส",
//     currentYear: 2,
//     facultyName: "คณะนิติศาสตร์",
//     subProgramName: "กฎหมายแพ่ง",
//     programName: "นิติศาสตร์",
//   },
//   {
//     studentId: 9,
//     studentCode: "62030009",
//     thaiName: "ธนวัฒน์ มณีรัตน์",
//     class: "ปวช",
//     currentYear: 1,
//     facultyName: "คณะเศรษฐศาสตร์",
//     subProgramName: "เศรษฐศาสตร์จุลภาค",
//     programName: "เศรษฐศาสตร์",
//   },
//   {
//     studentId: 10,
//     studentCode: "62040010",
//     thaiName: "กัญญา วัฒนสุข",
//     class: "ปวส",
//     currentYear: 1,
//     facultyName: "คณะแพทยศาสตร์",
//     subProgramName: "พยาบาลศาสตร์พื้นฐาน",
//     programName: "พยาบาลศาสตร์",
//   },
// ];

// export const mockStudentListByGroupID: GetStudentListByGroupIDDto = {
//   groupId: 101,
//   groupName: "2/1",
//   groupCode: "G201",
//   programName: "การบัญชี",
//   programId: 10,
//   facultyName: "บริหารธุรกิจ",
//   subProgramName: "บัญชีขั้นสูง",
//   class: "ปวช.",
//   students: [
//     {
//       prefix: "นาย",
//       studentCode: "65110001",
//       id: 1,
//       gender: "ชาย",
//       firstName: "กิตติ",
//       lastName: "ใจดี",
//       status: "ปกติ",
//     },
//     {
//       prefix: "นางสาว",
//       studentCode: "65110002",
//       id: 2,
//       gender: "หญิง",
//       firstName: "สุภาวดี",
//       lastName: "ทองสุข",
//       status: "ปกติ",
//     },
//     {
//       prefix: "นาย",
//       studentCode: "65110003",
//       id: 3,
//       gender: "ชาย",
//       firstName: "ณัฐวุฒิ",
//       lastName: "ดำรงค์",
//       status: "พักการเรียน",
//     },
//     {
//       prefix: "นางสาว",
//       studentCode: "65110004",
//       id: 4,
//       gender: "หญิง",
//       firstName: "พิมพ์ใจ",
//       lastName: "บุญมา",
//       status: "ปกติ",
//     },
//     {
//       prefix: "นาย",
//       studentCode: "65110005",
//       id: 5,
//       gender: "ชาย",
//       firstName: "ธีรภัทร",
//       lastName: "เก่งกล้า",
//       status: "ลาออก",
//     },
//     {
//       prefix: "นางสาว",
//       studentCode: "65110006",
//       id: 6,
//       gender: "หญิง",
//       firstName: "จิราพร",
//       lastName: "แสงทอง",
//       status: "ปกติ",
//     },
//     {
//       prefix: "นาย",
//       studentCode: "65110007",
//       id: 7,
//       gender: "ชาย",
//       firstName: "วีรภัทร",
//       lastName: "จันทรา",
//       status: "ปกติ",
//     },
//     {
//       prefix: "นางสาว",
//       studentCode: "65110008",
//       id: 8,
//       gender: "หญิง",
//       firstName: "อริสรา",
//       lastName: "รุ่งเรือง",
//       status: "ปกติ",
//     },
//     {
//       prefix: "นาย",
//       studentCode: "65110009",
//       id: 9,
//       gender: "ชาย",
//       firstName: "พงศกร",
//       lastName: "มีสุข",
//       status: "ปกติ",
//     },
//     {
//       prefix: "นางสาว",
//       studentCode: "65110010",
//       id: 10,
//       gender: "หญิง",
//       firstName: "ศิริพร",
//       lastName: "สดใส",
//       status: "ปกติ",
//     },
//   ],
// };


// export const mockTeacherDetailAndSchedule: TeacherDetailAndScheduleResponse = {
//   teacher: {
//     teacherId: 1,
//     firstName: "สมชาย",
//     lastName: "ใจดี",
//     prefix: "นาย",
//     gender: "ชาย",
//     teacherCode: "TCH001",
//     facultyId: 10,
//     facultyName: "คณะวิทยาศาสตร์",
//     program: "วิทยาการคอมพิวเตอร์",
//     phoneNumber: "0812345678",
//   },
//   schedule: [
//     {
//       scheduleSubjectId: 101,
//       day: "จันทร์",
//       period: 1,
//       room: "SC101",
//       subjectId: 201,
//       subjectName: "โครงสร้างข้อมูล",
//       subjectCode: "CS201",
//       term: "1",
//       year: 2568,
//       studentGroupId: 301,
//       studentGroupName: "CS ปี 2",
//       studentGroupCode: "CS2023",
//       studentCount: 35,
//       class: "2",
//       level: 2,
//       isComplete: false,
//       isPublish: true,
//       curriculumYear: 2566,
//     },
//     {
//       scheduleSubjectId: 102,
//       day: "พุธ",
//       period: 3,
//       room: "SC202",
//       subjectId: 202,
//       subjectName: "ระบบปฏิบัติการ",
//       subjectCode: "CS301",
//       term: "1",
//       year: 2568,
//       studentGroupId: 302,
//       studentGroupName: "CS ปี 3",
//       studentGroupCode: "CS2022",
//       studentCount: 40,
//       class: "3",
//       level: 3,
//       isComplete: true,
//       isPublish: true,
//       curriculumYear: 2565,
//     },
//     {
//       scheduleSubjectId: 103,
//       day: "ศุกร์",
//       period: 2,
//       room: "LAB1",
//       subjectId: 203,
//       subjectName: "การเขียนโปรแกรมเบื้องต้น",
//       subjectCode: "CS101",
//       term: "1",
//       year: 2568,
//       studentGroupId: 303,
//       studentGroupName: "CS ปี 1",
//       studentGroupCode: "CS2024",
//       studentCount: 50,
//       class: "1",
//       level: 1,
//       isComplete: false,
//       isPublish: false,
//       curriculumYear: 2568,
//     },
//   ],
// };
