services:
  obac-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - REACT_APP_API_URL=http://localhost:8080
