import {
  ConvertClassroomToExcelDto,
  convertGradBySubjectId,
} from "@/dto/gradDto";
import { StudentItems } from "@/dto/studentDto";
import { GeneralData, StudentListExcel } from "./generateExcelFile";

export const mockConvertGradBySubjectId: convertGradBySubjectId[] = [
  {
    studentCode: "65010001",
    name: "นาย สมชาย ใจดี",
    assignmentscore: 18,
    collectScore: 22,
    affectiveScore: 18,
    midtermScore: 14,
    finaltermScore: 16,
  },
  {
    studentCode: "65010002",
    name: "นางสาว สมหญิง รักเรียน",
    assignmentscore: 19,
    collectScore: 24,
    affectiveScore: 19,
    midtermScore: 16,
    finaltermScore: 17,
  },
  {
    studentCode: "65010003",
    name: "นาย วิชัย เก่งมาก",
    assignmentscore: 16,
    collectScore: 20,
    affectiveScore: 16,
    midtermScore: 12,
    finaltermScore: 14,
  },
  {
    studentCode: "65010004",
    name: "นางสาว มาลี สวยงาม",
    assignmentscore: 18,
    collectScore: 23,
    affectiveScore: 17,
    midtermScore: 15,
    finaltermScore: 16,
  },
  {
    studentCode: "65010005",
    name: "นาย ธนากร พยายาม",
    assignmentscore: 14,
    collectScore: 18,
    affectiveScore: 15,
    midtermScore: 11,
    finaltermScore: 12,
  },
  {
    studentCode: "65010006",
    name: "นางสาว จินตนา ฉลาดมาก",
    assignmentscore: 19,
    collectScore: 25,
    affectiveScore: 20,
    midtermScore: 17,
    finaltermScore: 18,
  },
  {
    studentCode: "65010007",
    name: "นาย ประยุทธ์ ขยันมาก",
    assignmentscore: 17,
    collectScore: 21,
    affectiveScore: 16,
    midtermScore: 13,
    finaltermScore: 15,
  },
  {
    studentCode: "65010008",
    name: "นางสาว อัญชลี น่ารัก",
    assignmentscore: 16,
    collectScore: 19,
    affectiveScore: 17,
    midtermScore: 12,
    finaltermScore: 13,
  },
];

export const mockStudentListByGroupID: StudentItems[] = [
  {
    prefix: "นาย",
    studentCode: "65010001",
    id: 1001,
    gender: "Male",
    firstName: "สมชาย",
    lastName: "ใจดี",
    status: "Active",
  },
  {
    prefix: "นางสาว",
    studentCode: "65010002",
    id: 1002,
    gender: "Female",
    firstName: "สมหญิง",
    lastName: "รักเรียน",
    status: "Active",
  },
  {
    prefix: "นาย",
    studentCode: "65010003",
    id: 1003,
    gender: "Male",
    firstName: "วิชัย",
    lastName: "เก่งมาก",
    status: "Active",
  },
  {
    prefix: "นางสาว",
    studentCode: "65010004",
    id: 1004,
    gender: "Female",
    firstName: "มาลี",
    lastName: "สวยงาม",
    status: "Active",
  },
  {
    prefix: "นาย",
    studentCode: "65010005",
    id: 1005,
    gender: "Male",
    firstName: "ธนากร",
    lastName: "พยายาม",
    status: "Active",
  },
  {
    prefix: "นางสาว",
    studentCode: "65010006",
    id: 1006,
    gender: "Female",
    firstName: "จินตนา",
    lastName: "ฉลาดมาก",
    status: "Active",
  },
  {
    prefix: "นาย",
    studentCode: "65010007",
    id: 1007,
    gender: "Male",
    firstName: "ประยุทธ์",
    lastName: "ขยันมาก",
    status: "Active",
  },
  {
    prefix: "นางสาว",
    studentCode: "65010008",
    id: 1008,
    gender: "Female",
    firstName: "อัญชลี",
    lastName: "น่ารัก",
    status: "Active",
  },
];

export const mockConvertClassroomToExcelDto: ConvertClassroomToExcelDto[] = [
  {
    studentCode: "65010001",
    name: "นาย สมชาย ใจดี",
  },
  {
    studentCode: "65010002",
    name: "นางสาว สมหญิง รักเรียน",
  },
  {
    studentCode: "65010003",
    name: "นาย วิชัย เก่งมาก",
  },
  {
    studentCode: "65010004",
    name: "นางสาว มาลี สวยงาม",
  },
  {
    studentCode: "65010005",
    name: "นาย ธนากร พยายาม",
  },
  {
    studentCode: "65010006",
    name: "นางสาว จินตนา ฉลาดมาก",
  },
  {
    studentCode: "65010007",
    name: "นาย ประยุทธ์ ขยันมาก",
  },
  {
    studentCode: "65010008",
    name: "นางสาว อัญชลี น่ารัก",
  },
];

export const mockGeneralData: GeneralData = {
  groupId: 101,
  groupName: "A",
  groupCode: "BUS101A",
  class: "ปวช.3",
  facultyName: "คณะบริหารธุรกิจ",
  programName: "การบัญชี",
  term: "1",
  year: 2567,
};

export const mockStudentList: StudentListExcel[] = [
  {
    studentId: 1001,
    studentCode: "65010001",
    name: "นาย สมชาย ใจดี",
    gpa: 3.25,
    gpax: 3.15,
    totalCredit: 18,
    subjects: {
      วิชาคณิตศาสตร์: "3.5",
      วิชาภาษาไทย: "4.0",
      วิชาภาษาอังกฤษ: "3.0",
      วิชาการบัญชี: "3.7",
      วิชาคอมพิวเตอร์: "3.5",
    },
  },
  {
    studentId: 1002,
    studentCode: "65010002",
    name: "นางสาว สมหญิง รักเรียน",
    gpa: 3.75,
    gpax: 3.68,
    totalCredit: 18,
    subjects: {
      วิชาคณิตศาสตร์: "4.0",
      วิชาภาษาไทย: "4.0",
      วิชาภาษาอังกฤษ: "3.5",
      วิชาการบัญชี: "4.0",
      วิชาคอมพิวเตอร์: "3.7",
    },
  },
  {
    studentId: 1003,
    studentCode: "65010003",
    name: "นาย วิชัย เก่งมาก",
    gpa: 2.85,
    gpax: 2.92,
    totalCredit: 18,
    subjects: {
      วิชาคณิตศาสตร์: "3.0",
      วิชาภาษาไทย: "3.5",
      วิชาภาษาอังกฤษ: "2.5",
      วิชาการบัญชี: "3.0",
      วิชาคอมพิวเตอร์: "2.7",
    },
  },
  {
    studentId: 1004,
    studentCode: "65010004",
    name: "นางสาว มาลี สวยงาม",
    gpa: 3.42,
    gpax: 3.38,
    totalCredit: 18,
    subjects: {
      วิชาคณิตศาสตร์: "3.7",
      วิชาภาษาไทย: "4.0",
      วิชาภาษาอังกฤษ: "3.5",
      วิชาการบัญชี: "3.5",
      วิชาคอมพิวเตอร์: "3.7",
    },
  },
  {
    studentId: 1005,
    studentCode: "65010005",
    name: "นาย ธนากร พยายาม",
    gpa: 2.58,
    gpax: 2.65,
    totalCredit: 18,
    subjects: {
      วิชาคณิตศาสตร์: "2.5",
      วิชาภาษาไทย: "3.0",
      วิชาภาษาอังกฤษ: "2.0",
      วิชาการบัญชี: "2.5",
      วิชาคอมพิวเตอร์: "2.7",
    },
  },
  {
    studentId: 1006,
    studentCode: "65010006",
    name: "นางสาว จินตนา ฉลาดมาก",
    gpa: 3.88,
    gpax: 3.85,
    totalCredit: 18,
    subjects: {
      วิชาคณิตศาสตร์: "4.0",
      วิชาภาษาไทย: "4.0",
      วิชาภาษาอังกฤษ: "3.7",
      วิชาการบัญชี: "4.0",
      วิชาคอมพิวเตอร์: "4.0",
    },
  },
  {
    studentId: 1007,
    studentCode: "65010007",
    name: "นาย ประยุทธ์ ขยันมาก",
    gpa: 3.12,
    gpax: 3.08,
    totalCredit: 18,
    subjects: {
      วิชาคณิตศาสตร์: "3.2",
      วิชาภาษาไทย: "3.5",
      วิชาภาษาอังกฤษ: "2.8",
      วิชาการบัญชี: "3.2",
      วิชาคอมพิวเตอร์: "3.0",
    },
  },
  {
    studentId: 1008,
    studentCode: "65010008",
    name: "นางสาว อัญชลี น่ารัก",
    gpa: 2.95,
    gpax: 2.98,
    totalCredit: 18,
    subjects: {
      วิชาคณิตศาสตร์: "2.8",
      วิชาภาษาไทย: "3.2",
      วิชาภาษาอังกฤษ: "2.7",
      วิชาการบัญชี: "3.0",
      วิชาคอมพิวเตอร์: "3.1",
    },
  },
];
