import { GetStudentGradeDetailDto, GradBelowResponse } from "@/dto/gradDto";
import { GroupSummaryGradeResponse } from "@/dto/gradingDto";
import { StudentNameListInSubject, StudentScorenSubject } from "@/dto/pdfDto";
import { StudentItems } from "@/dto/studentDto";
import { GetGradBelowResponse } from "@/lib/api/models/grade/grade.response";

export const GradSummaryGroupData: GetStudentGradeDetailDto = {
  gender: "ชาย",
  studentId: 1,
  firstName: "Krit",
  lastName: "Chaidee",
  thaiName: "กฤษณ์",
  thaiLastName: "ใจดี",
  class: "ปวช.2/1",
  currentYear: 2567,
  studentCode: "64110001",
  groupName: "การบัญชี",
  programName: "ประกาศนียบัตรวิชาชีพ",
  facultyName: "แผนกพาณิชยกรรม",
  subProgramName: "บัญชี",
  year: [
    {
      term: "1",
      year: 2567,
      totalCredit: 15,
      termQuery: [
        {
          subject_name: "ภาษาไทยเพื่อการสื่อสาร",
          subject_code: "20000-1101",
          gradeId: 1,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2.5,
          credit: "1",
          finalGrade: "2.5",
          remark: "",
        },
        {
          subject_name: "ภาษาอังกฤษเพื่อการสื่อสาร",
          subject_code: "20000-1203",
          gradeId: 2,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3,
          credit: "1",
          finalGrade: "3",
          remark: "",
        },
        {
          subject_name: "คณิตศาสตร์พื้นฐานอาชีพ",
          subject_code: "20000-1401",
          gradeId: 3,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 1.5,
          credit: "2",
          finalGrade: "1.5",
          remark: "",
        },
        {
          subject_name: "การขายและการตลาดเบื้องต้น",
          subject_code: "20200-1002",
          gradeId: 4,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3,
          credit: "2",
          finalGrade: "3",
          remark: "",
        },
        {
          subject_name: "การบัญชีเบื้องต้น",
          subject_code: "20200-1003",
          gradeId: 5,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2.5,
          credit: "3",
          finalGrade: "2.5",
          remark: "",
        },
        {
          subject_name: "พิมพ์ไทยคีบอร์ด",
          subject_code: "20200-1603",
          gradeId: 6,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2.5,
          credit: "2",
          finalGrade: "2.5",
          remark: "",
        },
      ],
    },
    {
      term: "2",
      year: 2567,
      totalCredit: 14,
      termQuery: [
        {
          subject_name: "ภาษาไทยเพื่ออาชีพ",
          subject_code: "20000-1102",
          gradeId: 7,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3.5,
          credit: "1",
          finalGrade: "3.5",
          remark: "",
        },
        {
          subject_name: "ภาษาอังกฤษเพื่อพัฒนาสุขภาพ",
          subject_code: "20000-1204",
          gradeId: 8,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3.5,
          credit: "1",
          finalGrade: "3.5",
          remark: "",
        },
        {
          subject_name: "วิทยาศาสตร์และคณิตฯ เบื้องต้น",
          subject_code: "20000-1402",
          gradeId: 9,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 1.5,
          credit: "2",
          finalGrade: "1.5",
          remark: "",
        },
        {
          subject_name: "การบัญชีห้างหุ้นส่วนเบื้องต้น",
          subject_code: "20200-1004",
          gradeId: 10,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3.5,
          credit: "3",
          finalGrade: "3.5",
          remark: "",
        },
      ],
    },
    {
      term: "1",
      year: 2566,
      totalCredit: 14,
      termQuery: [
        {
          subject_name: "ภาษาอังกฤษเบื้องต้น",
          subject_code: "20000-1201",
          gradeId: 11,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2,
          credit: "1",
          finalGrade: "2",
          remark: "",
        },
        {
          subject_name: "วิทยาศาสตร์พื้นฐาน",
          subject_code: "20000-1400",
          gradeId: 12,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2.5,
          credit: "2",
          finalGrade: "2.5",
          remark: "",
        },
      ],
    },
    {
      term: "2",
      year: 2566,
      totalCredit: 16,
      termQuery: [
        {
          subject_name: "คณิตศาสตร์ทั่วไป",
          subject_code: "20000-1403",
          gradeId: 13,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3,
          credit: "2",
          finalGrade: "3",
          remark: "",
        },
        {
          subject_name: "สังคมศึกษาเบื้องต้น",
          subject_code: "20000-1601",
          gradeId: 14,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2.5,
          credit: "2",
          finalGrade: "2.5",
          remark: "",
        },
      ],
    },
  ],
};

export const mockGroupSummaryGradeResponse: GroupSummaryGradeResponse = {
  groupId: 1,
  groupName: "ปวช.2/1",
  groupCode: "VOC2-1",
  class: "ปวช.2",
  facultyName: "บริหารธุรกิจ",
  programName: "การบัญชี",
  term: "1",
  year: 2568,
  subjects: [
    { subjectID: 101, subjectCode: "AC101", subjectName: "บัญชีขั้นต้น" },
    { subjectID: 102, subjectCode: "MA102", subjectName: "คณิตศาสตร์ธุรกิจ" },
    { subjectID: 103, subjectCode: "EC103", subjectName: "เศรษฐศาสตร์ทั่วไป" },
    { subjectID: 104, subjectCode: "EN104", subjectName: "ภาษาอังกฤษธุรกิจ" },
    { subjectID: 105, subjectCode: "MK105", subjectName: "การตลาดเบื้องต้น" },
  ],
  student: Array.from({ length: 28 }, (_, i) => {
    const gpa = 1 + Math.random() * 3;
    const gpax = 1 + Math.random() * 3;

    const grades = Array.from({ length: 5 }, (_, j) => {
      const allowedGrades = [0, 1, 1.5, 2, 2.5, 3, 3.5, 4];
      const gradeValue =
        allowedGrades[Math.floor(Math.random() * allowedGrades.length)];
      const remark = j === 3 && i % 2 === 0 ? "มผ" : "";
      return { grad: gradeValue, remark };
    });

    return {
      studentId: i + 1,
      prefix: "นาย",
      studentCode: `65110${i.toString().padStart(3, "0")}`,
      studentFirstName: `สมชาย${i + 1}`,
      studentLastName: `ใจดี`,
      gpa: +gpa.toFixed(2),
      gpax: +gpax.toFixed(2),
      totalCredit: 18,
      grads: grades,
    };
  }),
};

export function generateMockStudents(count: number): GradBelowResponse[] {
  const prefixes = ["นาย", "นางสาว"];
  const firstNames = [
    "จตุรงค์",
    "กัญญาณี",
    "พิมพ์พร",
    "สิรินยา",
    "ณัฐวุฒิ",
    "อรุณ",
    "สุชาติ",
    "มานพ",
    "วราภรณ์",
    "ปิยบุตร",
    "ธนพร",
    "เกษม",
    "ชลธิชา",
    "วุฒิชัย",
    "สายใจ",
    "อภิชาติ",
    "ดวงพร",
    "ศิริชัย",
    "สุพรรณี",
    "ยุทธนา",
  ];
  const lastNames = [
    "เรืองเกษม",
    "ชอบการ",
    "แก้วสวาสดิ์",
    "พิพัฒน์",
    "ใจดี",
    "หอมหวน",
    "มีนา",
    "ทองสุข",
    "สุขุมวาที",
    "เพชรดี",
    "โสมสกาว",
    "สมบูรณ์",
    "กาญจนพงศ์",
    "คชาภรณ์",
    "บวรศักดิ์",
    "เพชรสุวรรณ",
    "วัฒนศิริ",
    "รัตนชัย",
    "จันทร์เพ็ญ",
    "สุดา",
  ];

  const result: GradBelowResponse[] = [];

  for (let i = 1; i <= count; i++) {
    result.push({
      prefix: prefixes[Math.floor(Math.random() * prefixes.length)],
      studentId: i,
      studentCode: (6823000 + i).toString(),
      firstName: firstNames[Math.floor(Math.random() * firstNames.length)],
      lastName: lastNames[Math.floor(Math.random() * lastNames.length)],
      facultyName: "คณะบริหารธุรกิจ",
      programName: "การจัดการ",
      subProgramName: "การจัดการทั่วไป",
      class: `ปวช.${Math.floor(Math.random() * 3) + 1}`,
      currentLevel: Math.floor(Math.random() * 3) + 1,
      groupName: `ห้อง ${Math.floor(Math.random() * 5) + 1}/${
        Math.floor(Math.random() * 3) + 1
      }`,
      term: `${Math.floor(Math.random() * 2) + 1}`,
      year: 2568,
      gpax: parseFloat((Math.random() * 4).toFixed(2)),
    });
  }

  return result;
}

export const mockStudents = generateMockStudents(40);

export const mockStudentListByGroupID: StudentItems[] = [
  {
    prefix: "นาย",
    studentCode: "65110001",
    id: 1,
    gender: "ชาย",
    firstName: "กิตติ",
    lastName: "ใจดี",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110002",
    id: 2,
    gender: "หญิง",
    firstName: "อริสรา",
    lastName: "แสงทอง",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110003",
    id: 3,
    gender: "ชาย",
    firstName: "ธีรภัทร",
    lastName: "มีสุข",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110004",
    id: 4,
    gender: "หญิง",
    firstName: "พรนภา",
    lastName: "วัฒนะ",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110005",
    id: 5,
    gender: "ชาย",
    firstName: "นพดล",
    lastName: "รุ่งเรือง",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110006",
    id: 6,
    gender: "หญิง",
    firstName: "ชุติมา",
    lastName: "ทวีทรัพย์",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110007",
    id: 7,
    gender: "ชาย",
    firstName: "ปวริศ",
    lastName: "ทองแท้",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110008",
    id: 8,
    gender: "หญิง",
    firstName: "ธนภรณ์",
    lastName: "สายใจ",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110009",
    id: 9,
    gender: "ชาย",
    firstName: "พีระ",
    lastName: "แสงจันทร์",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110010",
    id: 10,
    gender: "หญิง",
    firstName: "มยุรี",
    lastName: "แก้วใส",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110011",
    id: 11,
    gender: "ชาย",
    firstName: "กฤษณ์",
    lastName: "เจริญผล",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110012",
    id: 12,
    gender: "หญิง",
    firstName: "ณัฐชา",
    lastName: "วรชาติ",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110013",
    id: 13,
    gender: "ชาย",
    firstName: "วีระพงษ์",
    lastName: "ตั้งมั่น",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110014",
    id: 14,
    gender: "หญิง",
    firstName: "อัจฉรา",
    lastName: "ใจดี",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110015",
    id: 15,
    gender: "ชาย",
    firstName: "พชร",
    lastName: "อรุณรุ่ง",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110001",
    id: 1,
    gender: "ชาย",
    firstName: "กิตติ",
    lastName: "ใจดี",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110002",
    id: 2,
    gender: "หญิง",
    firstName: "อริสรา",
    lastName: "แสงทอง",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110003",
    id: 3,
    gender: "ชาย",
    firstName: "ธีรภัทร",
    lastName: "มีสุข",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110004",
    id: 4,
    gender: "หญิง",
    firstName: "พรนภา",
    lastName: "วัฒนะ",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110005",
    id: 5,
    gender: "ชาย",
    firstName: "นพดล",
    lastName: "รุ่งเรือง",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110006",
    id: 6,
    gender: "หญิง",
    firstName: "ชุติมา",
    lastName: "ทวีทรัพย์",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110007",
    id: 7,
    gender: "ชาย",
    firstName: "ปวริศ",
    lastName: "ทองแท้",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110008",
    id: 8,
    gender: "หญิง",
    firstName: "ธนภรณ์",
    lastName: "สายใจ",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110009",
    id: 9,
    gender: "ชาย",
    firstName: "พีระ",
    lastName: "แสงจันทร์",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110010",
    id: 10,
    gender: "หญิง",
    firstName: "มยุรี",
    lastName: "แก้วใส",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110011",
    id: 11,
    gender: "ชาย",
    firstName: "กฤษณ์",
    lastName: "เจริญผล",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110012",
    id: 12,
    gender: "หญิง",
    firstName: "ณัฐชา",
    lastName: "วรชาติ",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110013",
    id: 13,
    gender: "ชาย",
    firstName: "วีระพงษ์",
    lastName: "ตั้งมั่น",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110014",
    id: 14,
    gender: "หญิง",
    firstName: "อัจฉรา",
    lastName: "ใจดี",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110015",
    id: 15,
    gender: "ชาย",
    firstName: "พชร",
    lastName: "อรุณรุ่ง",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110011",
    id: 11,
    gender: "ชาย",
    firstName: "กฤษณ์",
    lastName: "เจริญผล",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110012",
    id: 12,
    gender: "หญิง",
    firstName: "ณัฐชา",
    lastName: "วรชาติ",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110013",
    id: 13,
    gender: "ชาย",
    firstName: "วีระพงษ์",
    lastName: "ตั้งมั่น",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110014",
    id: 14,
    gender: "หญิง",
    firstName: "อัจฉรา",
    lastName: "ใจดี",
    status: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110015",
    id: 15,
    gender: "ชาย",
    firstName: "พชร",
    lastName: "อรุณรุ่ง",
    status: "กำลังศึกษา",
  },
];

export const mockStudentNameListInSubject: StudentNameListInSubject = {
  subjectID: 101,
  subjectCode: "AC101",
  subjectName: "บัญชีขั้นต้น",
  groupName: "ปวช.2/1",
  students: [
    {
      studentID: 1,
      studentCode: "65110001",
      prefix: "นาย",
      studentFirstName: "กิตติ",
      studentLastName: "ใจดี",
    },
    {
      studentID: 2,
      studentCode: "65110002",
      prefix: "นางสาว",
      studentFirstName: "อริสรา",
      studentLastName: "แสงทอง",
    },
    {
      studentID: 3,
      studentCode: "65110003",
      prefix: "นาย",
      studentFirstName: "ธีรภัทร",
      studentLastName: "มีสุข",
    },
    {
      studentID: 4,
      studentCode: "65110004",
      prefix: "นางสาว",
      studentFirstName: "พรนภา",
      studentLastName: "วัฒนะ",
    },
    {
      studentID: 5,
      studentCode: "65110005",
      prefix: "นาย",
      studentFirstName: "นพดล",
      studentLastName: "รุ่งเรือง",
    },
    {
      studentID: 6,
      studentCode: "65110006",
      prefix: "นางสาว",
      studentFirstName: "ชุติมา",
      studentLastName: "ทวีทรัพย์",
    },
    {
      studentID: 7,
      studentCode: "65110007",
      prefix: "นาย",
      studentFirstName: "ปวริศ",
      studentLastName: "ทองแท้",
    },
    {
      studentID: 8,
      studentCode: "65110008",
      prefix: "นางสาว",
      studentFirstName: "ธนภรณ์",
      studentLastName: "สายใจ",
    },
    {
      studentID: 9,
      studentCode: "65110009",
      prefix: "นาย",
      studentFirstName: "พีระ",
      studentLastName: "แสงจันทร์",
    },
    {
      studentID: 10,
      studentCode: "65110010",
      prefix: "นางสาว",
      studentFirstName: "มยุรี",
      studentLastName: "แก้วใส",
    },
    {
      studentID: 1,
      studentCode: "65110001",
      prefix: "นาย",
      studentFirstName: "กิตติ",
      studentLastName: "ใจดี",
    },
    {
      studentID: 2,
      studentCode: "65110002",
      prefix: "นางสาว",
      studentFirstName: "อริสรา",
      studentLastName: "แสงทอง",
    },
    {
      studentID: 3,
      studentCode: "65110003",
      prefix: "นาย",
      studentFirstName: "ธีรภัทร",
      studentLastName: "มีสุข",
    },
    {
      studentID: 4,
      studentCode: "65110004",
      prefix: "นางสาว",
      studentFirstName: "พรนภา",
      studentLastName: "วัฒนะ",
    },
    {
      studentID: 5,
      studentCode: "65110005",
      prefix: "นาย",
      studentFirstName: "นพดล",
      studentLastName: "รุ่งเรือง",
    },
    {
      studentID: 6,
      studentCode: "65110006",
      prefix: "นางสาว",
      studentFirstName: "ชุติมา",
      studentLastName: "ทวีทรัพย์",
    },
    {
      studentID: 7,
      studentCode: "65110007",
      prefix: "นาย",
      studentFirstName: "ปวริศ",
      studentLastName: "ทองแท้",
    },
    {
      studentID: 8,
      studentCode: "65110008",
      prefix: "นางสาว",
      studentFirstName: "ธนภรณ์",
      studentLastName: "สายใจ",
    },
    {
      studentID: 9,
      studentCode: "65110009",
      prefix: "นาย",
      studentFirstName: "พีระ",
      studentLastName: "แสงจันทร์",
    },
    {
      studentID: 10,
      studentCode: "65110010",
      prefix: "นางสาว",
      studentFirstName: "มยุรี",
      studentLastName: "แก้วใส",
    },
    {
      studentID: 1,
      studentCode: "65110001",
      prefix: "นาย",
      studentFirstName: "กิตติ",
      studentLastName: "ใจดี",
    },
    {
      studentID: 2,
      studentCode: "65110002",
      prefix: "นางสาว",
      studentFirstName: "อริสรา",
      studentLastName: "แสงทอง",
    },
    {
      studentID: 3,
      studentCode: "65110003",
      prefix: "นาย",
      studentFirstName: "ธีรภัทร",
      studentLastName: "มีสุข",
    },
    {
      studentID: 4,
      studentCode: "65110004",
      prefix: "นางสาว",
      studentFirstName: "พรนภา",
      studentLastName: "วัฒนะ",
    },
    {
      studentID: 5,
      studentCode: "65110005",
      prefix: "นาย",
      studentFirstName: "นพดล",
      studentLastName: "รุ่งเรือง",
    },
    {
      studentID: 6,
      studentCode: "65110006",
      prefix: "นางสาว",
      studentFirstName: "ชุติมา",
      studentLastName: "ทวีทรัพย์",
    },
    {
      studentID: 7,
      studentCode: "65110007",
      prefix: "นาย",
      studentFirstName: "ปวริศ",
      studentLastName: "ทองแท้",
    },
    {
      studentID: 8,
      studentCode: "65110008",
      prefix: "นางสาว",
      studentFirstName: "ธนภรณ์",
      studentLastName: "สายใจ",
    },
    {
      studentID: 9,
      studentCode: "65110009",
      prefix: "นาย",
      studentFirstName: "พีระ",
      studentLastName: "แสงจันทร์",
    },
    {
      studentID: 10,
      studentCode: "65110010",
      prefix: "นางสาว",
      studentFirstName: "มยุรี",
      studentLastName: "แก้วใส",
    },
    {
      studentID: 1,
      studentCode: "65110001",
      prefix: "นาย",
      studentFirstName: "กิตติ",
      studentLastName: "ใจดี",
    },
    {
      studentID: 2,
      studentCode: "65110002",
      prefix: "นางสาว",
      studentFirstName: "อริสรา",
      studentLastName: "แสงทอง",
    },
    {
      studentID: 3,
      studentCode: "65110003",
      prefix: "นาย",
      studentFirstName: "ธีรภัทร",
      studentLastName: "มีสุข",
    },
    {
      studentID: 4,
      studentCode: "65110004",
      prefix: "นางสาว",
      studentFirstName: "พรนภา",
      studentLastName: "วัฒนะ",
    },
    {
      studentID: 5,
      studentCode: "65110005",
      prefix: "นาย",
      studentFirstName: "นพดล",
      studentLastName: "รุ่งเรือง",
    },
    {
      studentID: 6,
      studentCode: "65110006",
      prefix: "นางสาว",
      studentFirstName: "ชุติมา",
      studentLastName: "ทวีทรัพย์",
    },
    {
      studentID: 7,
      studentCode: "65110007",
      prefix: "นาย",
      studentFirstName: "ปวริศ",
      studentLastName: "ทองแท้",
    },
    {
      studentID: 8,
      studentCode: "65110008",
      prefix: "นางสาว",
      studentFirstName: "ธนภรณ์",
      studentLastName: "สายใจ",
    },
    {
      studentID: 9,
      studentCode: "65110009",
      prefix: "นาย",
      studentFirstName: "พีระ",
      studentLastName: "แสงจันทร์",
    },
    {
      studentID: 10,
      studentCode: "65110010",
      prefix: "นางสาว",
      studentFirstName: "มยุรี",
      studentLastName: "แก้วใส",
    },
    {
      studentID: 1,
      studentCode: "65110001",
      prefix: "นาย",
      studentFirstName: "กิตติ",
      studentLastName: "ใจดี",
    },
    {
      studentID: 2,
      studentCode: "65110002",
      prefix: "นางสาว",
      studentFirstName: "อริสรา",
      studentLastName: "แสงทอง",
    },
    {
      studentID: 3,
      studentCode: "65110003",
      prefix: "นาย",
      studentFirstName: "ธีรภัทร",
      studentLastName: "มีสุข",
    },
    {
      studentID: 4,
      studentCode: "65110004",
      prefix: "นางสาว",
      studentFirstName: "พรนภา",
      studentLastName: "วัฒนะ",
    },
    {
      studentID: 5,
      studentCode: "65110005",
      prefix: "นาย",
      studentFirstName: "นพดล",
      studentLastName: "รุ่งเรือง",
    },
    {
      studentID: 6,
      studentCode: "65110006",
      prefix: "นางสาว",
      studentFirstName: "ชุติมา",
      studentLastName: "ทวีทรัพย์",
    },
    {
      studentID: 7,
      studentCode: "65110007",
      prefix: "นาย",
      studentFirstName: "ปวริศ",
      studentLastName: "ทองแท้",
    },
    {
      studentID: 8,
      studentCode: "65110008",
      prefix: "นางสาว",
      studentFirstName: "ธนภรณ์",
      studentLastName: "สายใจ",
    },
    {
      studentID: 9,
      studentCode: "65110009",
      prefix: "นาย",
      studentFirstName: "พีระ",
      studentLastName: "แสงจันทร์",
    },
    {
      studentID: 10,
      studentCode: "65110010",
      prefix: "นางสาว",
      studentFirstName: "มยุรี",
      studentLastName: "แก้วใส",
    },
  ],
};

import { StudentGroupGradeResponse } from "@/dto/gradDto";

export const mockStudentGroupGradeResponse: StudentGroupGradeResponse = {
  subjectName: "คณิตศาสตร์พื้นฐาน",
  subjectCode: "MATH101",
  credit: 3,
  hour: 45,
  subjectTeacher: "อาจารย์ณัฐวุฒิ ใจดี",
  subjectId: 101,
  groupId: 5,
  groupName: "ห้อง ม.4/1",
  groupCode: "G401",
  class: "ม.4",
  level: 4,
  isPublish: true,
  isComplete: false,
  term: "1",
  year: 2567,
  subjectGrades: [
    {
      studentId: 1001,
      studentCode: "64001",
      prefix: "นาย",
      status: "",
      firstName: "ศราวุธ",
      lastName: "แก้วใส",
      assignmentScore: 15,
      collectScore: 10,
      affectiveScore: 10,
      midtermScore: 15,
      finaltermScore: 20,
      totalScore: 70,
      finalGrade: 3,
      remarks: "",
    },
    {
      studentId: 1002,
      studentCode: "64002",
      status: "",
      prefix: "นางสาว",
      firstName: "ปวีณา",
      lastName: "สมใจ",
      assignmentScore: 14,
      collectScore: 8,
      affectiveScore: 10,
      midtermScore: 14,
      finaltermScore: 18,
      totalScore: 64,
      finalGrade: 2.5,
      remarks: "",
    },
    {
      studentId: 1003,
      status: "",
      studentCode: "64003",
      prefix: "นาย",
      firstName: "ชยพล",
      lastName: "สายใจ",
      assignmentScore: 13,
      collectScore: 9,
      affectiveScore: 9,
      midtermScore: 12,
      finaltermScore: 17,
      totalScore: 60,
      finalGrade: 2,
      remarks: "",
    },
    {
      studentId: 1004,
      studentCode: "64004",
      prefix: "นางสาว",
      status: "",
      firstName: "พรสุดา",
      lastName: "นิลวงศ์",
      assignmentScore: 10,
      collectScore: 6,
      affectiveScore: 8,
      midtermScore: 11,
      finaltermScore: 15,
      totalScore: 50,
      finalGrade: 1,
      remarks: "",
    },
    {
      studentId: 1005,
      studentCode: "64005",
      prefix: "นาย",
      firstName: "กิตติพงษ์",
      lastName: "ทองดี",
      status: "",
      assignmentScore: 9,
      collectScore: 5,
      affectiveScore: 6,
      midtermScore: 8,
      finaltermScore: 12,
      totalScore: 40,
      finalGrade: 0,
      remarks: "มผ.",
    },
    {
      studentId: 1006,
      status: "",
      studentCode: "64006",
      prefix: "นางสาว",
      firstName: "ธัญลักษณ์",
      lastName: "สุวรรณ",
      assignmentScore: 18,
      collectScore: 10,
      affectiveScore: 10,
      midtermScore: 20,
      finaltermScore: 25,
      totalScore: 83,
      finalGrade: 4,
      remarks: "",
    },
    {
      studentId: 1007,
      studentCode: "64007",
      status: "",
      prefix: "นาย",
      firstName: "ณัฐพล",
      lastName: "สายชล",
      assignmentScore: 16,
      collectScore: 9,
      affectiveScore: 9,
      midtermScore: 18,
      finaltermScore: 20,
      totalScore: 72,
      finalGrade: 3,
      remarks: "",
    },
    {
      studentId: 1008,
      status: "",
      studentCode: "64008",
      prefix: "นางสาว",
      firstName: "พัชรี",
      lastName: "วงศ์รักษ์",
      assignmentScore: 12,
      collectScore: 7,
      affectiveScore: 8,
      midtermScore: 10,
      finaltermScore: 14,
      totalScore: 51,
      finalGrade: 1,
      remarks: "",
    },
  ],
};

// export const mockGetGradBelowResponse: GetGradBelowResponse[] = [];

const prefixes = ["นาย", "นางสาว"];
const firstNames = [
  "กิตติ",
  "ณัฐวุฒิ",
  "อริสรา",
  "พรนภา",
  "สมชาย",
  "ชุติมา",
  "ธนภรณ์",
  "พีระ",
  "นพดล",
  "มยุรี",
];
const lastNames = [
  "ใจดี",
  "ทองคำ",
  "มีสุข",
  "รุ่งเรือง",
  "สีนวล",
  "ศรีสุข",
  "สายใจ",
  "ทองแท้",
  "วิเศษดี",
  "แก้วใส",
];
const groupNames = ["1/1", "1/2", "1/3", "2/1", "2/4", "2/10", "3/1"];

// for (let i = 1; i <= 45; i++) {
//   const index = (i - 1) % 10;
//   const group = groupNames[i % groupNames.length];

//   mockGetGradBelowResponse.push({
//     studentId: i,
//     prefix: prefixes[i % prefixes.length],
//     studentCode: `65110${i.toString().padStart(3, "0")}`,
//     firstName: firstNames[index],
//     lastName: lastNames[index],
//     facultyName: "บริหารธุรกิจ",
//     programName: "การบัญชี",
//     class: "ปวช.",
//     groupName: group,
//     term: "1",
//     year: 2568,
//     gpa: parseFloat((1.4 + Math.random() * 0.6).toFixed(2)), // 1.40 - 2.00
//   });
// }
