import { GetStudentGradeDetailDto } from "@/dto/gradDto";
import { GroupSummaryGradeResponse } from "@/dto/gradingDto";

export const GradSummaryGroupData: GetStudentGradeDetailDto = {
  gender: "ชาย",
  studentId: 1,
  firstName: "Krit",
  lastName: "Chaidee",
  thaiName: "กฤษณ์",
  thaiLastName: "ใจดี",
  class: "ปวช.2/1",
  currentYear: 2567,
  studentCode: "64110001",
  groupName: "การบัญชี",
  programName: "ประกาศนียบัตรวิชาชีพ",
  facultyName: "แผนกพาณิชยกรรม",
  subProgramName: "บัญชี",
  year: [
    {
      term: "1",
      year: 2567,
      totalCredit: 15,
      termQuery: [
        {
          subject_name: "ภาษาไทยเพื่อการสื่อสาร",
          subject_code: "20000-1101",
          gradeId: 1,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2.5,
          credit: "1",
          finalGrade: "2.5",
          remark: "",
        },
        {
          subject_name: "ภาษาอังกฤษเพื่อการสื่อสาร",
          subject_code: "20000-1203",
          gradeId: 2,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3,
          credit: "1",
          finalGrade: "3",
          remark: "",
        },
        {
          subject_name: "คณิตศาสตร์พื้นฐานอาชีพ",
          subject_code: "20000-1401",
          gradeId: 3,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 1.5,
          credit: "2",
          finalGrade: "1.5",
          remark: "",
        },
        {
          subject_name: "การขายและการตลาดเบื้องต้น",
          subject_code: "20200-1002",
          gradeId: 4,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3,
          credit: "2",
          finalGrade: "3",
          remark: "",
        },
        {
          subject_name: "การบัญชีเบื้องต้น",
          subject_code: "20200-1003",
          gradeId: 5,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2.5,
          credit: "3",
          finalGrade: "2.5",
          remark: "",
        },
        {
          subject_name: "พิมพ์ไทยคีบอร์ด",
          subject_code: "20200-1603",
          gradeId: 6,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2.5,
          credit: "2",
          finalGrade: "2.5",
          remark: "",
        },
      ],
    },
    {
      term: "2",
      year: 2567,
      totalCredit: 14,
      termQuery: [
        {
          subject_name: "ภาษาไทยเพื่ออาชีพ",
          subject_code: "20000-1102",
          gradeId: 7,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3.5,
          credit: "1",
          finalGrade: "3.5",
          remark: "",
        },
        {
          subject_name: "ภาษาอังกฤษเพื่อพัฒนาสุขภาพ",
          subject_code: "20000-1204",
          gradeId: 8,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3.5,
          credit: "1",
          finalGrade: "3.5",
          remark: "",
        },
        {
          subject_name: "วิทยาศาสตร์และคณิตฯ เบื้องต้น",
          subject_code: "20000-1402",
          gradeId: 9,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 1.5,
          credit: "2",
          finalGrade: "1.5",
          remark: "",
        },
        {
          subject_name: "การบัญชีห้างหุ้นส่วนเบื้องต้น",
          subject_code: "20200-1004",
          gradeId: 10,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3.5,
          credit: "3",
          finalGrade: "3.5",
          remark: "",
        },
      ],
    },
    {
      term: "1",
      year: 2566,
      totalCredit: 14,
      termQuery: [
        {
          subject_name: "ภาษาอังกฤษเบื้องต้น",
          subject_code: "20000-1201",
          gradeId: 11,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2,
          credit: "1",
          finalGrade: "2",
          remark: "",
        },
        {
          subject_name: "วิทยาศาสตร์พื้นฐาน",
          subject_code: "20000-1400",
          gradeId: 12,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2.5,
          credit: "2",
          finalGrade: "2.5",
          remark: "",
        },
      ],
    },
    {
      term: "2",
      year: 2566,
      totalCredit: 16,
      termQuery: [
        {
          subject_name: "คณิตศาสตร์ทั่วไป",
          subject_code: "20000-1403",
          gradeId: 13,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3,
          credit: "2",
          finalGrade: "3",
          remark: "",
        },
        {
          subject_name: "สังคมศึกษาเบื้องต้น",
          subject_code: "20000-1601",
          gradeId: 14,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2.5,
          credit: "2",
          finalGrade: "2.5",
          remark: "",
        },
      ],
    },
  ],
};

export const mockGroupSummaryGradeResponse: GroupSummaryGradeResponse = {
  groupId: 1,
  groupName: "ปวช.2/1",
  groupCode: "VOC2-1",
  class: "ปวช.2",
  facultyName: "บริหารธุรกิจ",
  programName: "การบัญชี",
  term: "1",
  year: 2568,
  subjects: [
    { subjectID: 101, subjectCode: "AC101", subjectName: "บัญชีขั้นต้น" },
    { subjectID: 102, subjectCode: "MA102", subjectName: "คณิตศาสตร์ธุรกิจ" },
    { subjectID: 103, subjectCode: "EC103", subjectName: "เศรษฐศาสตร์ทั่วไป" },
    { subjectID: 104, subjectCode: "EN104", subjectName: "ภาษาอังกฤษธุรกิจ" },
    { subjectID: 105, subjectCode: "MK105", subjectName: "การตลาดเบื้องต้น" },
  ],
  student: Array.from({ length: 10 }, (_, i) => {
    const gpa = 1 + Math.random() * 3;
    const gpax = 1 + Math.random() * 3;

    const grades = Array.from({ length: 5 }, (_, j) => {
      const allowedGrades = [0, 1, 1.5, 2, 2.5, 3, 3.5, 4];
      const gradeValue =
        allowedGrades[Math.floor(Math.random() * allowedGrades.length)];
      const remark = j === 3 && i % 2 === 0 ? "มผ" : "";
      return { grad: gradeValue, remark };
    });

    return {
      studentId: i + 1,
      prefix: "นาย",
      studentCode: `65110${i.toString().padStart(3, "0")}`,
      studentFirstName: `สมชาย${i + 1}`,
      studentLastName: `ใจดี`,
      gpa: +gpa.toFixed(2),
      gpax: +gpax.toFixed(2),
      totalCredit: 18,
      grads: grades,
    };
  }),
};
