import { GetStudentGradeDetailDto } from "@/dto/gradDto";
import { GroupSummaryGradeResponse } from "@/dto/gradingDto";
import { StudentNameListInSubject, StudentScorenSubject } from "@/dto/pdfDto";
import { StudentListByGroupIDDto } from "@/dto/studentDto";
import { GetGradBelowResponse } from "@/lib/api/models/grade/grade.response";

export const GradSummaryGroupData: GetStudentGradeDetailDto = {
  gender: "ชาย",
  studentId: 1,
  firstName: "Krit",
  lastName: "Chaidee",
  thaiName: "กฤษณ์",
  thaiLastName: "ใจดี",
  class: "ปวช.2/1",
  currentYear: 2567,
  studentCode: "64110001",
  groupName: "การบัญชี",
  programName: "ประกาศนียบัตรวิชาชีพ",
  facultyName: "แผนกพาณิชยกรรม",
  subProgramName: "บัญชี",
  year: [
    {
      term: "1",
      year: 2567,
      totalCredit: 15,
      termQuery: [
        {
          subject_name: "ภาษาไทยเพื่อการสื่อสาร",
          subject_code: "20000-1101",
          gradeId: 1,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2.5,
          credit: "1",
          finalGrade: "2.5",
          remark: "",
        },
        {
          subject_name: "ภาษาอังกฤษเพื่อการสื่อสาร",
          subject_code: "20000-1203",
          gradeId: 2,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3,
          credit: "1",
          finalGrade: "3",
          remark: "",
        },
        {
          subject_name: "คณิตศาสตร์พื้นฐานอาชีพ",
          subject_code: "20000-1401",
          gradeId: 3,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 1.5,
          credit: "2",
          finalGrade: "1.5",
          remark: "",
        },
        {
          subject_name: "การขายและการตลาดเบื้องต้น",
          subject_code: "20200-1002",
          gradeId: 4,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3,
          credit: "2",
          finalGrade: "3",
          remark: "",
        },
        {
          subject_name: "การบัญชีเบื้องต้น",
          subject_code: "20200-1003",
          gradeId: 5,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2.5,
          credit: "3",
          finalGrade: "2.5",
          remark: "",
        },
        {
          subject_name: "พิมพ์ไทยคีบอร์ด",
          subject_code: "20200-1603",
          gradeId: 6,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2.5,
          credit: "2",
          finalGrade: "2.5",
          remark: "",
        },
      ],
    },
    {
      term: "2",
      year: 2567,
      totalCredit: 14,
      termQuery: [
        {
          subject_name: "ภาษาไทยเพื่ออาชีพ",
          subject_code: "20000-1102",
          gradeId: 7,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3.5,
          credit: "1",
          finalGrade: "3.5",
          remark: "",
        },
        {
          subject_name: "ภาษาอังกฤษเพื่อพัฒนาสุขภาพ",
          subject_code: "20000-1204",
          gradeId: 8,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3.5,
          credit: "1",
          finalGrade: "3.5",
          remark: "",
        },
        {
          subject_name: "วิทยาศาสตร์และคณิตฯ เบื้องต้น",
          subject_code: "20000-1402",
          gradeId: 9,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 1.5,
          credit: "2",
          finalGrade: "1.5",
          remark: "",
        },
        {
          subject_name: "การบัญชีห้างหุ้นส่วนเบื้องต้น",
          subject_code: "20200-1004",
          gradeId: 10,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3.5,
          credit: "3",
          finalGrade: "3.5",
          remark: "",
        },
      ],
    },
    {
      term: "1",
      year: 2566,
      totalCredit: 14,
      termQuery: [
        {
          subject_name: "ภาษาอังกฤษเบื้องต้น",
          subject_code: "20000-1201",
          gradeId: 11,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2,
          credit: "1",
          finalGrade: "2",
          remark: "",
        },
        {
          subject_name: "วิทยาศาสตร์พื้นฐาน",
          subject_code: "20000-1400",
          gradeId: 12,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2.5,
          credit: "2",
          finalGrade: "2.5",
          remark: "",
        },
      ],
    },
    {
      term: "2",
      year: 2566,
      totalCredit: 16,
      termQuery: [
        {
          subject_name: "คณิตศาสตร์ทั่วไป",
          subject_code: "20000-1403",
          gradeId: 13,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 3,
          credit: "2",
          finalGrade: "3",
          remark: "",
        },
        {
          subject_name: "สังคมศึกษาเบื้องต้น",
          subject_code: "20000-1601",
          gradeId: 14,
          collectScore: null,
          testScore: null,
          affectiveScore: null,
          midtermScore: null,
          finalScore: null,
          totalScore: 2.5,
          credit: "2",
          finalGrade: "2.5",
          remark: "",
        },
      ],
    },
  ],
};

export const mockGroupSummaryGradeResponse: GroupSummaryGradeResponse = {
  groupId: 1,
  groupName: "ปวช.2/1",
  groupCode: "VOC2-1",
  class: "ปวช.2",
  facultyName: "บริหารธุรกิจ",
  programName: "การบัญชี",
  term: "1",
  year: 2568,
  subjects: [
    { subjectID: 101, subjectCode: "AC101", subjectName: "บัญชีขั้นต้น" },
    { subjectID: 102, subjectCode: "MA102", subjectName: "คณิตศาสตร์ธุรกิจ" },
    { subjectID: 103, subjectCode: "EC103", subjectName: "เศรษฐศาสตร์ทั่วไป" },
    { subjectID: 104, subjectCode: "EN104", subjectName: "ภาษาอังกฤษธุรกิจ" },
    { subjectID: 105, subjectCode: "MK105", subjectName: "การตลาดเบื้องต้น" },
  ],
  student: Array.from({ length: 10 }, (_, i) => {
    const gpa = 1 + Math.random() * 3;
    const gpax = 1 + Math.random() * 3;

    const grades = Array.from({ length: 5 }, (_, j) => {
      const allowedGrades = [0, 1, 1.5, 2, 2.5, 3, 3.5, 4];
      const gradeValue =
        allowedGrades[Math.floor(Math.random() * allowedGrades.length)];
      const remark = j === 3 && i % 2 === 0 ? "มผ" : "";
      return { grad: gradeValue, remark };
    });

    return {
      studentId: i + 1,
      prefix: "นาย",
      studentCode: `65110${i.toString().padStart(3, "0")}`,
      studentFirstName: `สมชาย${i + 1}`,
      studentLastName: `ใจดี`,
      gpa: +gpa.toFixed(2),
      gpax: +gpax.toFixed(2),
      totalCredit: 18,
      grads: grades,
    };
  }),
};

export const mockStudentListByGroupID: StudentListByGroupIDDto[] = [
  {
    prefix: "นาย",
    studentCode: "65110001",
    studentId: 1,
    gender: "ชาย",
    firstName: "กิตติ",
    lastName: "ใจดี",
    studentStatus: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110002",
    studentId: 2,
    gender: "หญิง",
    firstName: "อริสรา",
    lastName: "แสงทอง",
    studentStatus: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110003",
    studentId: 3,
    gender: "ชาย",
    firstName: "ธีรภัทร",
    lastName: "มีสุข",
    studentStatus: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110004",
    studentId: 4,
    gender: "หญิง",
    firstName: "พรนภา",
    lastName: "วัฒนะ",
    studentStatus: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110005",
    studentId: 5,
    gender: "ชาย",
    firstName: "นพดล",
    lastName: "รุ่งเรือง",
    studentStatus: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110006",
    studentId: 6,
    gender: "หญิง",
    firstName: "ชุติมา",
    lastName: "ทวีทรัพย์",
    studentStatus: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110007",
    studentId: 7,
    gender: "ชาย",
    firstName: "ปวริศ",
    lastName: "ทองแท้",
    studentStatus: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110008",
    studentId: 8,
    gender: "หญิง",
    firstName: "ธนภรณ์",
    lastName: "สายใจ",
    studentStatus: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110009",
    studentId: 9,
    gender: "ชาย",
    firstName: "พีระ",
    lastName: "แสงจันทร์",
    studentStatus: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110010",
    studentId: 10,
    gender: "หญิง",
    firstName: "มยุรี",
    lastName: "แก้วใส",
    studentStatus: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110011",
    studentId: 11,
    gender: "ชาย",
    firstName: "กฤษณ์",
    lastName: "เจริญผล",
    studentStatus: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110012",
    studentId: 12,
    gender: "หญิง",
    firstName: "ณัฐชา",
    lastName: "วรชาติ",
    studentStatus: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110013",
    studentId: 13,
    gender: "ชาย",
    firstName: "วีระพงษ์",
    lastName: "ตั้งมั่น",
    studentStatus: "กำลังศึกษา",
  },
  {
    prefix: "นางสาว",
    studentCode: "65110014",
    studentId: 14,
    gender: "หญิง",
    firstName: "อัจฉรา",
    lastName: "ใจดี",
    studentStatus: "กำลังศึกษา",
  },
  {
    prefix: "นาย",
    studentCode: "65110015",
    studentId: 15,
    gender: "ชาย",
    firstName: "พชร",
    lastName: "อรุณรุ่ง",
    studentStatus: "กำลังศึกษา",
  },
];

export const mockStudentNameListInSubject: StudentNameListInSubject = {
  subjectID: 101,
  subjectCode: "AC101",
  subjectName: "บัญชีขั้นต้น",
  groupName: "ปวช.2/1",
  students: [
    {
      studentID: 1,
      studentCode: "65110001",
      prefix: "นาย",
      studentFirstName: "กิตติ",
      studentLastName: "ใจดี",
    },
    {
      studentID: 2,
      studentCode: "65110002",
      prefix: "นางสาว",
      studentFirstName: "อริสรา",
      studentLastName: "แสงทอง",
    },
    {
      studentID: 3,
      studentCode: "65110003",
      prefix: "นาย",
      studentFirstName: "ธีรภัทร",
      studentLastName: "มีสุข",
    },
    {
      studentID: 4,
      studentCode: "65110004",
      prefix: "นางสาว",
      studentFirstName: "พรนภา",
      studentLastName: "วัฒนะ",
    },
    {
      studentID: 5,
      studentCode: "65110005",
      prefix: "นาย",
      studentFirstName: "นพดล",
      studentLastName: "รุ่งเรือง",
    },
    {
      studentID: 6,
      studentCode: "65110006",
      prefix: "นางสาว",
      studentFirstName: "ชุติมา",
      studentLastName: "ทวีทรัพย์",
    },
    {
      studentID: 7,
      studentCode: "65110007",
      prefix: "นาย",
      studentFirstName: "ปวริศ",
      studentLastName: "ทองแท้",
    },
    {
      studentID: 8,
      studentCode: "65110008",
      prefix: "นางสาว",
      studentFirstName: "ธนภรณ์",
      studentLastName: "สายใจ",
    },
    {
      studentID: 9,
      studentCode: "65110009",
      prefix: "นาย",
      studentFirstName: "พีระ",
      studentLastName: "แสงจันทร์",
    },
    {
      studentID: 10,
      studentCode: "65110010",
      prefix: "นางสาว",
      studentFirstName: "มยุรี",
      studentLastName: "แก้วใส",
    },
  ],
};

export const mockStudentScorenSubject: StudentScorenSubject = {
  subjectID: 101,
  subjectCode: "AC101",
  subjectName: "บัญชีขั้นต้น",
  groupName: "ปวช.2/1",
  students: Array.from({ length: 20 }, (_, i) => {
    const collect = Math.floor(Math.random() * 10) + 10;
    const test = Math.floor(Math.random() * 20) + 20;
    const affective = Math.floor(Math.random() * 10) + 5;
    const total = collect + test + affective;

    const gradeMap = (score: number): string => {
      if (score >= 80) return "4";
      if (score >= 75) return "3.5";
      if (score >= 70) return "3";
      if (score >= 65) return "2.5";
      if (score >= 60) return "2";
      if (score >= 55) return "1.5";
      if (score >= 50) return "1";
      return "0";
    };

    const grade = gradeMap(total);
    const remark = grade === "0" ? "ร" : "";

    return {
      studentId: i + 1,
      studentCode: `65110${(i + 1).toString().padStart(3, "0")}`,
      prefix: i % 2 === 0 ? "นาย" : "นางสาว",
      studentFirstName: i % 2 === 0 ? `สมชาย${i + 1}` : `สมหญิง${i + 1}`,
      studentLastName: "ใจดี",
      collectScore: collect,
      testScore: test,
      affectiveScore: affective,
      totalScore: total,
      grade: grade,
      remark: remark,
    };
  }),
};

export const mockGetGradBelowResponse: GetGradBelowResponse[] = [
  {
    studentId: 1,
    prefix:"นาย" ,
    studentCode: "65110001",
    firstName: "กิตติ",
    lastName: "ใจดี",
    facultyName: "บริหารธุรกิจ",
    programName: "การบัญชี",
    class: "ปวช.",
    groupName: "2/1",
    term: "1",
    year: 2568,
    gpa: 1.85,
  },
  {
    studentId: 2,
    studentCode: "65110002",
    prefix:"นาย" ,
    firstName: "ณัฐวุฒิ",
    lastName: "ทองคำ",
    facultyName: "บริหารธุรกิจ",
    programName: "การบัญชี",
    class: "ปวช",
    groupName: "3/1",
    term: "1",
    year: 2568,
    gpa: 1.9,
  },
  {
    studentId: 3,
    studentCode: "65110003",
    prefix:"นาย" ,
    firstName: "อริสรา",
    lastName: "มีสุข",
    facultyName: "บริหารธุรกิจ",
    programName: "การบัญชี",
    class: "ปวช",
    groupName: "2/10",
    term: "1",
    year: 2568,
    gpa: 1.75,
  },
  {
    studentId: 4,
    studentCode: "65110004",
    prefix:"นาย" ,
    firstName: "พรนภา",
    lastName: "รุ่งเรือง",
    facultyName: "บริหารธุรกิจ",
    programName: "การบัญชี",
    class: "ปวช",
    groupName: "1/4",
    term: "1",
    year: 2568,
    gpa: 1.6,
  },
  {
    studentId: 5,
    studentCode: "65110005",
    prefix:"นาย" ,
    firstName: "สมชาย",
    lastName: "สีนวล",
    facultyName: "บริหารธุรกิจ",
    programName: "การบัญชี",
    class: "ปวช",
    groupName: "1/4",
    term: "1",
    year: 2568,
    gpa: 1.95,
  },
  {
    studentId: 6,
    studentCode: "65110006",
    prefix:"นาย" ,
    firstName: "ชุติมา",
    lastName: "ศรีสุข",
    facultyName: "บริหารธุรกิจ",
    programName: "การบัญชี",
    class: "ปวช",
    groupName: "2/4",
    term: "1",
    year: 2568,
    gpa: 1.7,
  },
  {
    studentId: 7,
    studentCode: "65110007",
    prefix:"นาย" ,
    firstName: "ธนภรณ์",
    lastName: "สายใจ",
    facultyName: "บริหารธุรกิจ",
    programName: "การบัญชี",
    class: "ปวช",
    groupName: "2/4",
    term: "1",
    year: 2568,
    gpa: 1.8,
  },
  {
    studentId: 8,
    studentCode: "65110008",
    prefix:"นาย" ,
    firstName: "พีระ",
    lastName: "ทองแท้",
    facultyName: "บริหารธุรกิจ",
    programName: "การบัญชี",
    class: "ปวช",
    groupName: "2/4",
    term: "1",
    year: 2568,
    gpa: 1.65,
  },
  {
    studentId: 9,
    studentCode: "65110009",
    prefix:"นาย" ,
    firstName: "นพดล",
    lastName: "วิเศษดี",
    facultyName: "บริหารธุรกิจ",
    programName: "การบัญชี",
    class: "ปวช",
    groupName: "2/1",
    term: "1",
    year: 2568,
    gpa: 1.5,
  },
  {
    studentId: 10,
    studentCode: "65110010",
    prefix:"นาย" ,
    firstName: "มยุรี",
    lastName: "แก้วใส",
    facultyName: "บริหารธุรกิจ",
    programName: "การบัญชี",
    class: "ปวช",
    groupName: "2/1",
    term: "1",
    year: 2568,
    gpa: 1.45,
  },
];
