import "@app/styles/globals.css";
import { NavbarRegisterStudent } from "./student/navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <NavbarRegisterStudent />{children}</body>
    </html>
  );
}
