import "@app/styles/globals.css";
import { NavbarRegisterStudent } from "./navbar";
import HomeFooter from "@/components/common/Footer/HomeFooter";


export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <NavbarRegisterStudent />{children}<HomeFooter/></body>
    </html>
  );
}
