import HomeFooter from "@/components/common/Footer/HomeFooter";
import { HomePageNavBar } from "@/components/common/NavBar/HomePageNavBar";
import "@app/styles/globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


export const metadata = {
  title: "OBAC Authentication",
  description: "Generated by FavTeam",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ToastContainer
          position="bottom-right"
          hideProgressBar
          className="z-50"
        />
        <HomePageNavBar />
        <div className="mt-24">
        {children}
        </div>
        <HomeFooter/>
      </body>
    </html>
  );
}
