
import "@app/styles/globals.css";
import { AcademicSidebar } from "./sidebar/academicSidebar";
import { AcademicSideBarData, ProfileData } from "@/resource/academics/sidebarData";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body><AcademicSidebar
          menuItems={AcademicSideBarData.menuItems}
          profileData={ProfileData}
        />{children}</body>
    </html>
  )
}
