import type { Metadata } from "next";
import React from "react";
import "@app/styles/globals.css";

export const metadata: Metadata = {
  title: "OBAC-student.ac.th",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
