import { GradStudentInSubject, StudentGroupGradeResponse } from "@/dto/gradDto";
import { GetStudentDetailAndSummaryScoreByStudentCodeResponse } from "@/dto/gradingDto";
import { CardSubjectResponse } from "@/dto/teacherDto";

export const mockCardSubjectResponse: CardSubjectResponse[] = [
  {
    scheduleSubjectId: 1,
    day: "วันจันทร์",
    period: 1,
    room: "101",
    subjectId: 101,
    subjectName: "การบริหารจัดการทั่วไป",
    subjectCode: "MG201",
    term: "1",
    year: 2567,
    studentGroupId: 1,
    studentGroupName: "1/2",
    studentGroupCode: "A1",
    class: "ปวช",
    level: 1,
    studentAmount: 30,
    isComplete: false,
    isPublish: false,
    timing: 0,
  },
  {
    scheduleSubjectId: 2,
    day: "วันพุธ",
    period: 3,
    room: "102",
    subjectId: 102,
    subjectName: "ความรู้เบื้องต้นเกี่ยวกับคอมพิวเตอร์",
    subjectCode: "CS101",
    term: "1",
    year: 2567,
    studentGroupId: 1,
    studentGroupName: "1/4",
    studentGroupCode: "A1",
    class: "ปวช",
    level: 1,
    studentAmount: 30,
    isComplete: false,
    isPublish: false,
    timing: 0,
  },
  {
    scheduleSubjectId: 3,
    day: "วันศุกร์",
    period: 2,
    room: "203",
    subjectId: 103,
    subjectName: "ภาษาอังกฤษธุรกิจ",
    subjectCode: "EN102",
    term: "1",
    year: 2567,
    studentGroupId: 1,
    studentGroupName: "2/2",
    studentGroupCode: "A1",
    class: "ปวช",
    level: 1,
    studentAmount: 30,
    isComplete: true,
    isPublish: true,
    timing: 0,
  },
];
export const mockStudentGroupGradeResponse: StudentGroupGradeResponse = {
  subjectName: "คณิตศาสตร์",
  subjectCode: "MATH101",
  subjectId: 1,
  groupName: "2/1",
  groupCode: "G21",
  class: "ปวช.",
  level: 1,
  isPublish: true,
  isComplete: true,
  term: "1",
  year: 2568,
  subjectGrades: [
    {
      studentId: 1,
      studentCode: "65110001",
      firstName: "กิตติ",
      lastName: "ใจดี",
      assignmentScore: 8,
      collectScore: 9,
      affectiveScore: 10,
      midtermScore: 20,
      finaltermScore: 45,
      totalScore: 92,
      finalGrade: 4,
      remarks: "น.ร.",
    },
    {
      studentId: 2,
      studentCode: "65110002",
      firstName: "ณัฐวุฒิ",
      lastName: "ทองคำ",
      assignmentScore: 7,
      collectScore: 8,
      affectiveScore: 9,
      midtermScore: 18,
      finaltermScore: 42,
      totalScore: 84,
      finalGrade: 3.5,
      remarks: "ข.ป.",
    },
    {
      studentId: 3,
      studentCode: "65110003",
      firstName: "พิมพ์ใจ",
      lastName: "ศรีสุข",
      assignmentScore: 6,
      collectScore: 7,
      affectiveScore: 8,
      midtermScore: 17,
      finaltermScore: 38,
      totalScore: 76,
      finalGrade: 3,
      remarks: "ถ.ล.",
    },
    {
      studentId: 4,
      studentCode: "65110004",
      firstName: "วุฒิชัย",
      lastName: "แสงทอง",
      assignmentScore: 5,
      collectScore: 6,
      affectiveScore: 7,
      midtermScore: 16,
      finaltermScore: 35,
      totalScore: 69,
      finalGrade: 2.5,
      remarks: "ถ.พ.",
    },
    {
      studentId: 5,
      studentCode: "65110005",
      firstName: "ธนพร",
      lastName: "แก้วใส",
      assignmentScore: 5,
      collectScore: 5,
      affectiveScore: 6,
      midtermScore: 15,
      finaltermScore: 33,
      totalScore: 64,
      finalGrade: 2,
      remarks: "ท.",
    },
    {
      studentId: 6,
      studentCode: "65110006",
      firstName: "อังคณา",
      lastName: "บุญเรือง",
      assignmentScore: 6,
      collectScore: 6,
      affectiveScore: 6,
      midtermScore: 14,
      finaltermScore: 30,
      totalScore: 62,
      finalGrade: 2,
      remarks: "ม.ส.",
    },
    {
      studentId: 7,
      studentCode: "65110007",
      firstName: "สุเมธ",
      lastName: "สิงห์โต",
      assignmentScore: 4,
      collectScore: 5,
      affectiveScore: 5,
      midtermScore: 13,
      finaltermScore: 28,
      totalScore: 55,
      finalGrade: 1.5,
      remarks: "ผ.",
    },
    {
      studentId: 8,
      studentCode: "65110008",
      firstName: "กมลวรรณ",
      lastName: "แสงดาว",
      assignmentScore: 4,
      collectScore: 4,
      affectiveScore: 4,
      midtermScore: 10,
      finaltermScore: 25,
      totalScore: 47,
      finalGrade: 1,
      remarks: "ถ.น.",
    },
    {
      studentId: 9,
      studentCode: "65110009",
      firstName: "ชัยวัฒน์",
      lastName: "ยอดดี",
      assignmentScore: 3,
      collectScore: 3,
      affectiveScore: 4,
      midtermScore: 9,
      finaltermScore: 20,
      totalScore: 39,
      finalGrade: 0.5,
      remarks: "ม.ผ.",
    },
    {
      studentId: 10,
      studentCode: "65110010",
      firstName: "ณัฐธิดา",
      lastName: "งามสง่า",
      assignmentScore: 2,
      collectScore: 2,
      affectiveScore: 3,
      midtermScore: 7,
      finaltermScore: 18,
      totalScore: 32,
      finalGrade: 0,
      remarks: "",
    },
  ],
};

export const mockStudentDetailAndSummary: GetStudentDetailAndSummaryScoreByStudentCodeResponse =
  {
    student: {
      id: 1,
      prefix: "นาย",
      name: "กิตติ",
      lastName: "ใจดี",
      gender: "ชาย",
      nationality: "ไทย",
      birthDate: "2005-08-15",
      citizenId: "1234567890123",
      studentCode: "65110001",
      phoneNumber: "0812345678",
      studentGroupId: 101,
      groupName: "2/1",
      groupCode: "G21",
      class: "ปวช.",
      level: 2,
      programName: "การบัญชี",
      subProgramName: "บัญชีธุรกิจ",
      facultyName: "บริหารธุรกิจ",
      gpax: 3.42,
      status: "กำลังศึกษา",
    },
    termYearGradeGroups: [
      {
        term: "1",
        year: 2566,
        totalGPA: 3.25,
        totalCredit: 18,
        grades: [
          {
            gradeId: 1001,
            finalGrade: 90,
            remark: "",
            subjectName: "คณิตศาสตร์พื้นฐาน",
            subjectCode: "MTH101",
            credit: 3,
            gradePoint: 4.0,
            term: "1",
            year: 2566,
          },
          {
            gradeId: 1002,
            finalGrade: 85,
            remark: "",
            subjectName: "ภาษาอังกฤษ",
            subjectCode: "ENG101",
            credit: 3,
            gradePoint: 3.5,
            term: "1",
            year: 2566,
          },
        ],
      },
      {
        term: "2",
        year: 2566,
        totalGPA: 3.1,
        totalCredit: 20,
        grades: [
          {
            gradeId: 1003,
            finalGrade: 88,
            remark: "",
            subjectName: "วิทยาศาสตร์ทั่วไป",
            subjectCode: "SCI101",
            credit: 3,
            gradePoint: 3.75,
            term: "2",
            year: 2566,
          },
          {
            gradeId: 1004,
            finalGrade: 80,
            remark: "",
            subjectName: "สุขศึกษา",
            subjectCode: "HEA101",
            credit: 2,
            gradePoint: 3.0,
            term: "2",
            year: 2566,
          },
        ],
      },
      {
        term: "1",
        year: 2567,
        totalGPA: 3.5,
        totalCredit: 19,
        grades: [
          {
            gradeId: 1005,
            finalGrade: 95,
            remark: "",
            subjectName: "คอมพิวเตอร์เบื้องต้น",
            subjectCode: "COM101",
            credit: 3,
            gradePoint: 4.0,
            term: "1",
            year: 2567,
          },
        ],
      },
      {
        term: "2",
        year: 2567,
        totalGPA: 3.2,
        totalCredit: 21,
        grades: [
          {
            gradeId: 1006,
            finalGrade: 78,
            remark: "สอบซ่อม",
            subjectName: "เคมีพื้นฐาน",
            subjectCode: "CHE101",
            credit: 3,
            gradePoint: 2.75,
            term: "2",
            year: 2567,
          },
        ],
      },
      {
        term: "1",
        year: 2568,
        totalGPA: 3.6,
        totalCredit: 22,
        grades: [
          {
            gradeId: 1007,
            finalGrade: 92,
            remark: "",
            subjectName: "ฟิสิกส์เบื้องต้น",
            subjectCode: "PHY101",
            credit: 3,
            gradePoint: 4.0,
            term: "1",
            year: 2568,
          },
        ],
      },
    ],
  };
