import { GradStudentInSubject } from "@/dto/gradDto";
import { CardSubjectResponse } from "@/dto/teacherDto";

export const mockCardSubjectResponse: CardSubjectResponse[] = [
  {
    scheduleSubjectId: 1,
    day: "วันจันทร์",
    period: 1,
    room: "101",
    subjectId: 101,
    subjectName: "การบริหารจัดการทั่วไป",
    subjectCode: "MG201",
    term: "1",
    year: 2567,
    studentGroupId: 1,
    studentGroupName: "1/2",
    studentGroupCode: "A1",
    class: "ปวช",
    level: 1,
    studentAmount: 30,
    isComplete: false,
    isPublish: false,
  },
  {
    scheduleSubjectId: 2,
    day: "วันพุธ",
    period: 3,
    room: "102",
    subjectId: 102,
    subjectName: "ความรู้เบื้องต้นเกี่ยวกับคอมพิวเตอร์",
    subjectCode: "CS101",
    term: "1",
    year: 2567,
    studentGroupId: 1,
    studentGroupName: "1/4",
    studentGroupCode: "A1",
    class: "ปวช",
    level: 1,
    studentAmount: 30,
    isComplete: false,
    isPublish: false,
  },
  {
    scheduleSubjectId: 3,
    day: "วันศุกร์",
    period: 2,
    room: "203",
    subjectId: 103,
    subjectName: "ภาษาอังกฤษธุรกิจ",
    subjectCode: "EN102",
    term: "1",
    year: 2567,
    studentGroupId: 1,
    studentGroupName: "2/2",
    studentGroupCode: "A1",
    class: "ปวช",
    level: 1,
    studentAmount: 30,
    isComplete: true,
    isPublish: true,
  }
];

export const mockGradStudentInSubject: GradStudentInSubject[] = [
  {
    gradeId: 1,
    subjectId: 101,
    scheduleSubjectId: 201,
    studentGroup: "ปวช.2/1",
    studentId: 1,
    studentCode: "65110001",
    gender: "ชาย",
    firstName: "กิตติ",
    lastName: "ใจดี",
    subjectName: "บัญชีขั้นต้น",
    collectScore: 10,
    testScore: 25,
    affectiveScore: 5,
    totalScore: 40,
    grade: "1",
    remark: "",
  },
  {
    gradeId: 2,
    subjectId: 101,
    scheduleSubjectId: 201,
    studentGroup: "ปวช.2/1",
    studentId: 2,
    studentCode: "65110002",
    gender: "หญิง",
    firstName: "อริสรา",
    lastName: "แสงทอง",
    subjectName: "บัญชีขั้นต้น",
    collectScore: 15,
    testScore: 30,
    affectiveScore: 5,
    totalScore: 50,
    grade: "2",
    remark: "",
  },
  {
    gradeId: 3,
    subjectId: 101,
    scheduleSubjectId: 201,
    studentGroup: "ปวช.2/1",
    studentId: 3,
    studentCode: "65110003",
    gender: "ชาย",
    firstName: "ธีรภัทร",
    lastName: "มีสุข",
    subjectName: "บัญชีขั้นต้น",
    collectScore: 20,
    testScore: 30,
    affectiveScore: 10,
    totalScore: 60,
    grade: "2.5",
    remark: "",
  },
  {
    gradeId: 4,
    subjectId: 101,
    scheduleSubjectId: 201,
    studentGroup: "ปวช.2/1",
    studentId: 4,
    studentCode: "65110004",
    gender: "หญิง",
    firstName: "พรนภา",
    lastName: "วัฒนะ",
    subjectName: "บัญชีขั้นต้น",
    collectScore: 25,
    testScore: 25,
    affectiveScore: 5,
    totalScore: 55,
    grade: "2",
    remark: "",
  },
  {
    gradeId: 5,
    subjectId: 101,
    scheduleSubjectId: 201,
    studentGroup: "ปวช.2/1",
    studentId: 5,
    studentCode: "65110005",
    gender: "ชาย",
    firstName: "นพดล",
    lastName: "รุ่งเรือง",
    subjectName: "บัญชีขั้นต้น",
    collectScore: 30,
    testScore: 35,
    affectiveScore: 10,
    totalScore: 75,
    grade: "3.5",
    remark: "",
  },
  {
    gradeId: 6,
    subjectId: 101,
    scheduleSubjectId: 201,
    studentGroup: "ปวช.2/1",
    studentId: 6,
    studentCode: "65110006",
    gender: "หญิง",
    firstName: "ชุติมา",
    lastName: "ทวีทรัพย์",
    subjectName: "บัญชีขั้นต้น",
    collectScore: 25,
    testScore: 40,
    affectiveScore: 10,
    totalScore: 75,
    grade: "3.5",
    remark: "",
  },
  {
    gradeId: 7,
    subjectId: 101,
    scheduleSubjectId: 201,
    studentGroup: "ปวช.2/1",
    studentId: 7,
    studentCode: "65110007",
    gender: "ชาย",
    firstName: "ปวริศ",
    lastName: "ทองแท้",
    subjectName: "บัญชีขั้นต้น",
    collectScore: 20,
    testScore: 20,
    affectiveScore: 5,
    totalScore: 45,
    grade: "1.5",
    remark: "",
  },
  {
    gradeId: 8,
    subjectId: 101,
    scheduleSubjectId: 201,
    studentGroup: "ปวช.2/1",
    studentId: 8,
    studentCode: "65110008",
    gender: "หญิง",
    firstName: "ธนภรณ์",
    lastName: "สายใจ",
    subjectName: "บัญชีขั้นต้น",
    collectScore: 10,
    testScore: 10,
    affectiveScore: 5,
    totalScore: 25,
    grade: "0",
    remark: "ร",
  },
  {
    gradeId: 9,
    subjectId: 101,
    scheduleSubjectId: 201,
    studentGroup: "ปวช.2/1",
    studentId: 9,
    studentCode: "65110009",
    gender: "ชาย",
    firstName: "พีระ",
    lastName: "แสงจันทร์",
    subjectName: "บัญชีขั้นต้น",
    collectScore: 28,
    testScore: 25,
    affectiveScore: 7,
    totalScore: 60,
    grade: "2.5",
    remark: "",
  },
  {
    gradeId: 10,
    subjectId: 101,
    scheduleSubjectId: 201,
    studentGroup: "ปวช.2/1",
    studentId: 10,
    studentCode: "65110010",
    gender: "หญิง",
    firstName: "มยุรี",
    lastName: "แก้วใส",
    subjectName: "บัญชีขั้นต้น",
    collectScore: 35,
    testScore: 40,
    affectiveScore: 10,
    totalScore: 85,
    grade: "4",
    remark: "",
  },
];
