import { CardSubjectResponse } from "@/dto/teacherDto";

export const mockCardSubjectResponse: CardSubjectResponse[] = [
  {
    scheduleSubjectId: 1,
    day: "วันจันทร์",
    period: 1,
    room: "101",
    subjectId: 101,
    subjectName: "การบริหารจัดการทั่วไป",
    subjectCode: "MG201",
    term: "1",
    year: 2567,
    studentGroupId: 1,
    studentGroupName: "1/2",
    studentGroupCode: "A1",
    class: "ปวช",
    level: 1,
    studentAmount: 30,
    isComplete: false,
    isPublish: false,
  },
  {
    scheduleSubjectId: 2,
    day: "วันพุธ",
    period: 3,
    room: "102",
    subjectId: 102,
    subjectName: "ความรู้เบื้องต้นเกี่ยวกับคอมพิวเตอร์",
    subjectCode: "CS101",
    term: "1",
    year: 2567,
    studentGroupId: 1,
    studentGroupName: "1/4",
    studentGroupCode: "A1",
    class: "ปวช",
    level: 1,
    studentAmount: 30,
    isComplete: false,
    isPublish: false,
  },
  {
    scheduleSubjectId: 3,
    day: "วันศุกร์",
    period: 2,
    room: "203",
    subjectId: 103,
    subjectName: "ภาษาอังกฤษธุรกิจ",
    subjectCode: "EN102",
    term: "1",
    year: 2567,
    studentGroupId: 1,
    studentGroupName: "2/2",
    studentGroupCode: "A1",
    class: "ปวช",
    level: 1,
    studentAmount: 30,
    isComplete: true,
    isPublish: true,
  }
];
