import { TeacherSideBarData } from "@/resource/teachers/sidebarData"
import { TeacherSidebar } from "./sidebar/teacherSidebar"
import "@app/styles/globals.css";
import { ProfileData } from "@/resource/students/sidebarData"
import type { Metadata } from "next";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body><TeacherSidebar
          menuItems={TeacherSideBarData.menuItems}
          profileData={ProfileData}
        />{children}</body>
    </html>
  )
}
