import { StudentTranscriptData } from "@/dto/studentDto";

export const mockStudentTranscriptList: StudentTranscriptData[] = [
  {
    studentId: 1,
    firstName: "อรทัย",
    lastName: "ตั้งใจ",
    thaiName: "อรทัย",
    thaiLastName: "ตั้งใจ",
    class: "ปวช 1/1",
    currentYear: 2568,
    studentCode: "65000001",
    groupName: "MK13A",
    programName: "การตลาด",
    facultyName: "บริการและการจัดการ",
    subProgramName: "ไม่มีข้อมูล",
    year: [
      {
        term: "1",
        year: 2568,
        totalCredit: 13,
        termQuery: [
          {
            subject_name: "คณิตศาสตร์",
            subject_code: "MATH101",
            credit: "3",
            finalGrade: "0",
            remark: "",
            collectScore: 25,
            affectiveScore: 10,
            testScore: 15,
            gradeId: 101,
          },
          {
            subject_name: "ภาษาไทย",
            subject_code: "THAI101",
            credit: "2",
            finalGrade: "1.0",
            remark: "",
            collectScore: 30,
            affectiveScore: 15,
            testScore: 25,
            gradeId: 102,
          },
          {
            subject_name: "ภาษาอังกฤษ",
            subject_code: "ENG101",
            credit: "3",
            finalGrade: "2.5",
            remark: "",
            collectScore: 35,
            affectiveScore: 20,
            testScore: 30,
            gradeId: 103,
          },
          {
            subject_name: "วิทยาศาสตร์",
            subject_code: "SCI101",
            credit: "3",
            finalGrade: "0",
            remark: "",
            collectScore: 22,
            affectiveScore: 10,
            testScore: 18,
            gradeId: 104,
          },
          {
            subject_name: "ประวัติศาสตร์",
            subject_code: "HIST101",
            credit: "2",
            finalGrade: "0",
            remark: "",
            collectScore: 20,
            affectiveScore: 10,
            testScore: 20,
            gradeId: 105,
          },
        ],
      },
    ],
  },
  {
    studentId: 2,
    firstName: "วิชัย",
    lastName: "ใจดี",
    thaiName: "วิชัย",
    thaiLastName: "ใจดี",
    class: "ปวช 1/1",
    currentYear: 2568,
    studentCode: "65000002",
    groupName: "MK13A",
    programName: "การตลาด",
    facultyName: "บริการและการจัดการ",
    subProgramName: "ไม่มีข้อมูล",
    year: [
      {
        term: "1",
        year: 2568,
        totalCredit: 13,
        termQuery: [
          {
            subject_name: "คณิตศาสตร์",
            subject_code: "MATH101",
            credit: "3",
            finalGrade: "3.0",
            remark: "",
            collectScore: 35,
            affectiveScore: 15,
            testScore: 40,
            gradeId: 201,
          },
          {
            subject_name: "ภาษาไทย",
            subject_code: "THAI101",
            credit: "2",
            finalGrade: "4.0",
            remark: "ผ.",
            collectScore: 38,
            affectiveScore: 18,
            testScore: 40,
            gradeId: 202,
          },
          {
            subject_name: "ภาษาอังกฤษ",
            subject_code: "ENG101",
            credit: "3",
            finalGrade: "3.5",
            remark: "",
            collectScore: 34,
            affectiveScore: 20,
            testScore: 36,
            gradeId: 203,
          },
          {
            subject_name: "วิทยาศาสตร์",
            subject_code: "SCI101",
            credit: "3",
            finalGrade: "0",
            remark: "",
            collectScore: 22,
            affectiveScore: 10,
            testScore: 18,
            gradeId: 204,
          },
          {
            subject_name: "ประวัติศาสตร์",
            subject_code: "HIST101",
            credit: "2",
            finalGrade: "3.5",
            remark: "",
            collectScore: 30,
            affectiveScore: 10,
            testScore: 35,
            gradeId: 205,
          },
        ],
      },
    ],
  },
  {
    studentId: 3,
    firstName: "วิชัยเอ",
    lastName: "ใจสิงค์",
    thaiName: "วิชัยเอ",
    thaiLastName: "ใจสิงค์",
    class: "ปวช 1/1",
    currentYear: 2568,
    studentCode: "65000003",
    groupName: "MK13A",
    programName: "การตลาด",
    facultyName: "บริการและการจัดการ",
    subProgramName: "ไม่มีข้อมูล",
    year: [
      {
        term: "1",
        year: 2568,
        totalCredit: 13,
        termQuery: [
          {
            subject_name: "คณิตศาสตร์",
            subject_code: "MATH101",
            credit: "3",
            finalGrade: "3.0",
            remark: "",
            collectScore: 35,
            affectiveScore: 15,
            testScore: 40,
            gradeId: 301,
          },
          {
            subject_name: "ภาษาไทย",
            subject_code: "THAI101",
            credit: "2",
            finalGrade: "4.0",
            remark: "",
            collectScore: 38,
            affectiveScore: 18,
            testScore: 40,
            gradeId: 302,
          },
          {
            subject_name: "ภาษาอังกฤษ",
            subject_code: "ENG101",
            credit: "3",
            finalGrade: "3.5",
            remark: "",
            collectScore: 34,
            affectiveScore: 20,
            testScore: 36,
            gradeId: 303,
          },
          {
            subject_name: "วิทยาศาสตร์",
            subject_code: "SCI101",
            credit: "3",
            finalGrade: "0",
            remark: "",
            collectScore: 22,
            affectiveScore: 10,
            testScore: 18,
            gradeId: 304,
          },
          {
            subject_name: "ประวัติศาสตร์",
            subject_code: "HIST101",
            credit: "2",
            finalGrade: "3.5",
            remark: "",
            collectScore: 30,
            affectiveScore: 10,
            testScore: 35,
            gradeId: 305,
          },
        ],
      },
    ],
  },
  {
    studentId: 4,
    firstName: "นพมล",
    lastName: "แซ่ลิ้ม",
    thaiName: "นพมล",
    thaiLastName: "แซ่ลิ้ม",
    class: "ปวช 1/1",
    currentYear: 2568,
    studentCode: "65000004",
    groupName: "MK13A",
    programName: "การตลาด",
    facultyName: "บริการและการจัดการ",
    subProgramName: "ไม่มีข้อมูล",
    year: [
      {
        term: "1",
        year: 2568,
        totalCredit: 13,
        termQuery: [
          {
            subject_name: "คณิตศาสตร์",
            subject_code: "MATH101",
            credit: "3",
            finalGrade: "3.0",
            remark: "",
            collectScore: 35,
            affectiveScore: 15,
            testScore: 40,
            gradeId: 401,
          },
          {
            subject_name: "ภาษาไทย",
            subject_code: "THAI101",
            credit: "2",
            finalGrade: "4.0",
            remark: "",
            collectScore: 38,
            affectiveScore: 18,
            testScore: 40,
            gradeId: 402,
          },
          {
            subject_name: "ภาษาอังกฤษ",
            subject_code: "ENG101",
            credit: "3",
            finalGrade: "3.5",
            remark: "",
            collectScore: 34,
            affectiveScore: 20,
            testScore: 36,
            gradeId: 403,
          },
          {
            subject_name: "วิทยาศาสตร์",
            subject_code: "SCI101",
            credit: "3",
            finalGrade: "0",
            remark: "",
            collectScore: 22,
            affectiveScore: 10,
            testScore: 18,
            gradeId: 404,
          },
          {
            subject_name: "ประวัติศาสตร์",
            subject_code: "HIST101",
            credit: "2",
            finalGrade: "3.5",
            remark: "",
            collectScore: 30,
            affectiveScore: 10,
            testScore: 35,
            gradeId: 405,
          },
        ],
      },
    ],
  },
];
