import "@app/styles/globals.css";
import { AcademicSidebar } from "../../../components/common/SideBar/AcademicSidebar";
import {
  AcademicSideBarData,
  ProfileData,
} from "@/resource/academics/sidebarData";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "OBAC-วิชาการ.ac.th",
  description: "Generated by FavTeam",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ToastContainer
          position="bottom-right"
          hideProgressBar
          className="z-50"
        />
        <AcademicSidebar
          menuItems={AcademicSideBarData.menuItems}
          profileData={ProfileData}
        />
        <div className="pt-20 lg:pl-10">{children}</div>
      </body>
    </html>
  );
}
